
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  common_api: 'common_api',
  common_user: 'common_user',
  common_usergroup: 'common_usergroup',
  common_usergroupmenu: 'common_usergroupmenu'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const Common_apiScalarFieldEnum = {
  api_id: 'api_id',
  api_type: 'api_type',
  api_name: 'api_name',
  api_path: 'api_path',
  api_function: 'api_function',
  auth_flag: 'auth_flag',
  api_remark: 'api_remark',
  state: 'state',
  updated_at: 'updated_at',
  created_at: 'created_at'
} as const

export type Common_apiScalarFieldEnum = (typeof Common_apiScalarFieldEnum)[keyof typeof Common_apiScalarFieldEnum]


export const Common_userScalarFieldEnum = {
  user_id: 'user_id',
  user_username: 'user_username',
  user_type: 'user_type',
  user_email: 'user_email',
  user_country_code: 'user_country_code',
  user_phone: 'user_phone',
  user_discord: 'user_discord',
  user_telegram: 'user_telegram',
  user_account: 'user_account',
  user_password: 'user_password',
  user_password_error: 'user_password_error',
  user_login_time: 'user_login_time',
  user_name: 'user_name',
  user_gender: 'user_gender',
  user_avatar: 'user_avatar',
  user_province: 'user_province',
  user_city: 'user_city',
  user_district: 'user_district',
  user_address: 'user_address',
  user_zipcode: 'user_zipcode',
  user_company: 'user_company',
  user_remark: 'user_remark',
  state: 'state',
  updated_at: 'updated_at',
  created_at: 'created_at'
} as const

export type Common_userScalarFieldEnum = (typeof Common_userScalarFieldEnum)[keyof typeof Common_userScalarFieldEnum]


export const Common_usergroupScalarFieldEnum = {
  usergroup_id: 'usergroup_id',
  organization_id: 'organization_id',
  usergroup_type: 'usergroup_type',
  usergroup_code: 'usergroup_code',
  usergroup_name: 'usergroup_name',
  node_type: 'node_type',
  parent_id: 'parent_id',
  state: 'state',
  updated_at: 'updated_at',
  created_at: 'created_at'
} as const

export type Common_usergroupScalarFieldEnum = (typeof Common_usergroupScalarFieldEnum)[keyof typeof Common_usergroupScalarFieldEnum]


export const Common_usergroupmenuScalarFieldEnum = {
  usergroupmenu_id: 'usergroupmenu_id',
  usergroup_id: 'usergroup_id',
  menu_id: 'menu_id',
  state: 'state',
  updated_at: 'updated_at',
  created_at: 'created_at'
} as const

export type Common_usergroupmenuScalarFieldEnum = (typeof Common_usergroupmenuScalarFieldEnum)[keyof typeof Common_usergroupmenuScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

