
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model common_api
 * 
 */
export type common_api = Prisma.common_apiModel
/**
 * Model common_user
 * 
 */
export type common_user = Prisma.common_userModel
/**
 * Model common_usergroup
 * 
 */
export type common_usergroup = Prisma.common_usergroupModel
/**
 * Model common_usergroupmenu
 * 
 */
export type common_usergroupmenu = Prisma.common_usergroupmenuModel
