
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model common_api
 * 
 */
export type common_api = Prisma.common_apiModel
/**
 * Model common_group
 * 
 */
export type common_group = Prisma.common_groupModel
/**
 * Model common_group_menu
 * 
 */
export type common_group_menu = Prisma.common_group_menuModel
/**
 * Model common_system_menu
 * 
 */
export type common_system_menu = Prisma.common_system_menuModel
/**
 * Model common_user
 * 
 */
export type common_user = Prisma.common_userModel
/**
 * Model common_user_group
 * 
 */
export type common_user_group = Prisma.common_user_groupModel
