const errorList: { [index: string]: any } = {
  common_01: 'Method not supported',
  common_02: 'Unknown',
  common_03: 'Invalidate input',
  common_api_01: 'Already exists',
  common_api_02: 'Item does not exist',
  common_api_03: 'Unknown file type',
  common_api_04: 'The folder is not empty',
  group_01: 'Group already exists',
  group_02: 'Group does not exist',
  group_03: 'No path',
  group_04: 'There are users under the group',
  group_05: 'Role already exists',
  group_06: 'The folder is not empty',
  group_07: 'Organization does not exist',
  group_08: 'user does not under the group',
  usersetting_01: 'wrong password',
  usersetting_02: 'User does not exist',
  usersetting_03: 'User does not belong to this organization',
  operator_01: 'Group does not exist',
  operator_02: 'User already exists',
  operator_03: 'User does not exist',
  menu_01: 'Menu already exists',
  menu_02: 'Menu does not exist',
  menu_03: 'Folder is not empty',
  menu_04: 'Unknown path',
  auth_01: 'User does not exist',
  auth_02: 'User already exists',
  auth_03: 'User does not exist or password is wrong',
  auth_04: 'Captcha error',
  auth_05: 'Captcha error',
  auth_06: 'Requested too frequently',
  auth_09: 'Unknown default group',
  auth_10: 'Wrong phone number',
  auth_11: 'Forbidden',
  auth_12: 'Sms failed',
  auth_13: 'Phone number has been bound',
  template_01: 'Template already exists',
  org_01: 'Organization already exists',
  org_02: 'No default organization',
  org_03: 'Not affiliated with the organization',
  zkpass_01: 'Too many submits',
  project_01: 'Too many projects',
  project_02: 'Missing required items',
  provider_01: 'state error',
  provider_02: 'reward required',
  provider_03: 'task state error',
  zkpass_sdk_01: 'Request task fail',
  zkpass_sdk_02: 'Origin not allow',
  zkpass_sdk_03: 'Schema does not exist',
  zkpass_sdk_04: 'Task does not exist',
  zkpass_sdk_05: 'Token mismatch',
}
export default errorList
