
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_user_group` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_user_group
 * 
 */
export type common_user_groupModel = runtime.Types.Result.DefaultSelection<Prisma.$common_user_groupPayload>

export type AggregateCommon_user_group = {
  _count: Common_user_groupCountAggregateOutputType | null
  _avg: Common_user_groupAvgAggregateOutputType | null
  _sum: Common_user_groupSumAggregateOutputType | null
  _min: Common_user_groupMinAggregateOutputType | null
  _max: Common_user_groupMaxAggregateOutputType | null
}

export type Common_user_groupAvgAggregateOutputType = {
  user_group_id: number | null
  group_id: number | null
}

export type Common_user_groupSumAggregateOutputType = {
  user_group_id: number | null
  group_id: number | null
}

export type Common_user_groupMinAggregateOutputType = {
  user_group_id: number | null
  user_id: string | null
  group_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_user_groupMaxAggregateOutputType = {
  user_group_id: number | null
  user_id: string | null
  group_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_user_groupCountAggregateOutputType = {
  user_group_id: number
  user_id: number
  group_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_user_groupAvgAggregateInputType = {
  user_group_id?: true
  group_id?: true
}

export type Common_user_groupSumAggregateInputType = {
  user_group_id?: true
  group_id?: true
}

export type Common_user_groupMinAggregateInputType = {
  user_group_id?: true
  user_id?: true
  group_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_user_groupMaxAggregateInputType = {
  user_group_id?: true
  user_id?: true
  group_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_user_groupCountAggregateInputType = {
  user_group_id?: true
  user_id?: true
  group_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_user_groupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_user_group to aggregate.
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_user_groups to fetch.
   */
  orderBy?: Prisma.common_user_groupOrderByWithRelationInput | Prisma.common_user_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_user_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_user_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_user_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_user_groups
  **/
  _count?: true | Common_user_groupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_user_groupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_user_groupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_user_groupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_user_groupMaxAggregateInputType
}

export type GetCommon_user_groupAggregateType<T extends Common_user_groupAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_user_group]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_user_group[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_user_group[P]>
}




export type common_user_groupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_user_groupWhereInput
  orderBy?: Prisma.common_user_groupOrderByWithAggregationInput | Prisma.common_user_groupOrderByWithAggregationInput[]
  by: Prisma.Common_user_groupScalarFieldEnum[] | Prisma.Common_user_groupScalarFieldEnum
  having?: Prisma.common_user_groupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_user_groupCountAggregateInputType | true
  _avg?: Common_user_groupAvgAggregateInputType
  _sum?: Common_user_groupSumAggregateInputType
  _min?: Common_user_groupMinAggregateInputType
  _max?: Common_user_groupMaxAggregateInputType
}

export type Common_user_groupGroupByOutputType = {
  user_group_id: number
  user_id: string
  group_id: number
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_user_groupCountAggregateOutputType | null
  _avg: Common_user_groupAvgAggregateOutputType | null
  _sum: Common_user_groupSumAggregateOutputType | null
  _min: Common_user_groupMinAggregateOutputType | null
  _max: Common_user_groupMaxAggregateOutputType | null
}

type GetCommon_user_groupGroupByPayload<T extends common_user_groupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_user_groupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_user_groupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_user_groupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_user_groupGroupByOutputType[P]>
      }
    >
  >



export type common_user_groupWhereInput = {
  AND?: Prisma.common_user_groupWhereInput | Prisma.common_user_groupWhereInput[]
  OR?: Prisma.common_user_groupWhereInput[]
  NOT?: Prisma.common_user_groupWhereInput | Prisma.common_user_groupWhereInput[]
  user_group_id?: Prisma.IntFilter<"common_user_group"> | number
  user_id?: Prisma.StringFilter<"common_user_group"> | string
  group_id?: Prisma.IntFilter<"common_user_group"> | number
  state?: Prisma.StringFilter<"common_user_group"> | string
  updated_at?: Prisma.DateTimeFilter<"common_user_group"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_user_group"> | Date | string
}

export type common_user_groupOrderByWithRelationInput = {
  user_group_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_user_groupWhereUniqueInput = Prisma.AtLeast<{
  user_group_id?: number
  AND?: Prisma.common_user_groupWhereInput | Prisma.common_user_groupWhereInput[]
  OR?: Prisma.common_user_groupWhereInput[]
  NOT?: Prisma.common_user_groupWhereInput | Prisma.common_user_groupWhereInput[]
  user_id?: Prisma.StringFilter<"common_user_group"> | string
  group_id?: Prisma.IntFilter<"common_user_group"> | number
  state?: Prisma.StringFilter<"common_user_group"> | string
  updated_at?: Prisma.DateTimeFilter<"common_user_group"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_user_group"> | Date | string
}, "user_group_id">

export type common_user_groupOrderByWithAggregationInput = {
  user_group_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_user_groupCountOrderByAggregateInput
  _avg?: Prisma.common_user_groupAvgOrderByAggregateInput
  _max?: Prisma.common_user_groupMaxOrderByAggregateInput
  _min?: Prisma.common_user_groupMinOrderByAggregateInput
  _sum?: Prisma.common_user_groupSumOrderByAggregateInput
}

export type common_user_groupScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_user_groupScalarWhereWithAggregatesInput | Prisma.common_user_groupScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_user_groupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_user_groupScalarWhereWithAggregatesInput | Prisma.common_user_groupScalarWhereWithAggregatesInput[]
  user_group_id?: Prisma.IntWithAggregatesFilter<"common_user_group"> | number
  user_id?: Prisma.StringWithAggregatesFilter<"common_user_group"> | string
  group_id?: Prisma.IntWithAggregatesFilter<"common_user_group"> | number
  state?: Prisma.StringWithAggregatesFilter<"common_user_group"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_user_group"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_user_group"> | Date | string
}

export type common_user_groupCreateInput = {
  user_id: string
  group_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_user_groupUncheckedCreateInput = {
  user_group_id?: number
  user_id: string
  group_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_user_groupUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_user_groupUncheckedUpdateInput = {
  user_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_user_groupCreateManyInput = {
  user_group_id?: number
  user_id: string
  group_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_user_groupUpdateManyMutationInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_user_groupUncheckedUpdateManyInput = {
  user_group_id?: Prisma.IntFieldUpdateOperationsInput | number
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_user_groupCountOrderByAggregateInput = {
  user_group_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_user_groupAvgOrderByAggregateInput = {
  user_group_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
}

export type common_user_groupMaxOrderByAggregateInput = {
  user_group_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_user_groupMinOrderByAggregateInput = {
  user_group_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_user_groupSumOrderByAggregateInput = {
  user_group_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
}



export type common_user_groupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_group_id?: boolean
  user_id?: boolean
  group_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user_group"]>

export type common_user_groupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_group_id?: boolean
  user_id?: boolean
  group_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user_group"]>

export type common_user_groupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_group_id?: boolean
  user_id?: boolean
  group_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user_group"]>

export type common_user_groupSelectScalar = {
  user_group_id?: boolean
  user_id?: boolean
  group_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_user_groupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_group_id" | "user_id" | "group_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_user_group"]>

export type $common_user_groupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_user_group"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_group_id: number
    user_id: string
    group_id: number
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_user_group"]>
  composites: {}
}

export type common_user_groupGetPayload<S extends boolean | null | undefined | common_user_groupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload, S>

export type common_user_groupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_user_groupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_user_groupCountAggregateInputType | true
  }

export interface common_user_groupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_user_group'], meta: { name: 'common_user_group' } }
  /**
   * Find zero or one Common_user_group that matches the filter.
   * @param {common_user_groupFindUniqueArgs} args - Arguments to find a Common_user_group
   * @example
   * // Get one Common_user_group
   * const common_user_group = await prisma.common_user_group.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_user_groupFindUniqueArgs>(args: Prisma.SelectSubset<T, common_user_groupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_user_group that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_user_groupFindUniqueOrThrowArgs} args - Arguments to find a Common_user_group
   * @example
   * // Get one Common_user_group
   * const common_user_group = await prisma.common_user_group.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_user_groupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_user_groupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_user_group that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupFindFirstArgs} args - Arguments to find a Common_user_group
   * @example
   * // Get one Common_user_group
   * const common_user_group = await prisma.common_user_group.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_user_groupFindFirstArgs>(args?: Prisma.SelectSubset<T, common_user_groupFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_user_group that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupFindFirstOrThrowArgs} args - Arguments to find a Common_user_group
   * @example
   * // Get one Common_user_group
   * const common_user_group = await prisma.common_user_group.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_user_groupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_user_groupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_user_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_user_groups
   * const common_user_groups = await prisma.common_user_group.findMany()
   * 
   * // Get first 10 Common_user_groups
   * const common_user_groups = await prisma.common_user_group.findMany({ take: 10 })
   * 
   * // Only select the `user_group_id`
   * const common_user_groupWithUser_group_idOnly = await prisma.common_user_group.findMany({ select: { user_group_id: true } })
   * 
   */
  findMany<T extends common_user_groupFindManyArgs>(args?: Prisma.SelectSubset<T, common_user_groupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_user_group.
   * @param {common_user_groupCreateArgs} args - Arguments to create a Common_user_group.
   * @example
   * // Create one Common_user_group
   * const Common_user_group = await prisma.common_user_group.create({
   *   data: {
   *     // ... data to create a Common_user_group
   *   }
   * })
   * 
   */
  create<T extends common_user_groupCreateArgs>(args: Prisma.SelectSubset<T, common_user_groupCreateArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_user_groups.
   * @param {common_user_groupCreateManyArgs} args - Arguments to create many Common_user_groups.
   * @example
   * // Create many Common_user_groups
   * const common_user_group = await prisma.common_user_group.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_user_groupCreateManyArgs>(args?: Prisma.SelectSubset<T, common_user_groupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_user_groups and returns the data saved in the database.
   * @param {common_user_groupCreateManyAndReturnArgs} args - Arguments to create many Common_user_groups.
   * @example
   * // Create many Common_user_groups
   * const common_user_group = await prisma.common_user_group.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_user_groups and only return the `user_group_id`
   * const common_user_groupWithUser_group_idOnly = await prisma.common_user_group.createManyAndReturn({
   *   select: { user_group_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_user_groupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_user_groupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_user_group.
   * @param {common_user_groupDeleteArgs} args - Arguments to delete one Common_user_group.
   * @example
   * // Delete one Common_user_group
   * const Common_user_group = await prisma.common_user_group.delete({
   *   where: {
   *     // ... filter to delete one Common_user_group
   *   }
   * })
   * 
   */
  delete<T extends common_user_groupDeleteArgs>(args: Prisma.SelectSubset<T, common_user_groupDeleteArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_user_group.
   * @param {common_user_groupUpdateArgs} args - Arguments to update one Common_user_group.
   * @example
   * // Update one Common_user_group
   * const common_user_group = await prisma.common_user_group.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_user_groupUpdateArgs>(args: Prisma.SelectSubset<T, common_user_groupUpdateArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_user_groups.
   * @param {common_user_groupDeleteManyArgs} args - Arguments to filter Common_user_groups to delete.
   * @example
   * // Delete a few Common_user_groups
   * const { count } = await prisma.common_user_group.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_user_groupDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_user_groupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_user_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_user_groups
   * const common_user_group = await prisma.common_user_group.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_user_groupUpdateManyArgs>(args: Prisma.SelectSubset<T, common_user_groupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_user_groups and returns the data updated in the database.
   * @param {common_user_groupUpdateManyAndReturnArgs} args - Arguments to update many Common_user_groups.
   * @example
   * // Update many Common_user_groups
   * const common_user_group = await prisma.common_user_group.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_user_groups and only return the `user_group_id`
   * const common_user_groupWithUser_group_idOnly = await prisma.common_user_group.updateManyAndReturn({
   *   select: { user_group_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_user_groupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_user_groupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_user_group.
   * @param {common_user_groupUpsertArgs} args - Arguments to update or create a Common_user_group.
   * @example
   * // Update or create a Common_user_group
   * const common_user_group = await prisma.common_user_group.upsert({
   *   create: {
   *     // ... data to create a Common_user_group
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_user_group we want to update
   *   }
   * })
   */
  upsert<T extends common_user_groupUpsertArgs>(args: Prisma.SelectSubset<T, common_user_groupUpsertArgs<ExtArgs>>): Prisma.Prisma__common_user_groupClient<runtime.Types.Result.GetResult<Prisma.$common_user_groupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_user_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupCountArgs} args - Arguments to filter Common_user_groups to count.
   * @example
   * // Count the number of Common_user_groups
   * const count = await prisma.common_user_group.count({
   *   where: {
   *     // ... the filter for the Common_user_groups we want to count
   *   }
   * })
  **/
  count<T extends common_user_groupCountArgs>(
    args?: Prisma.Subset<T, common_user_groupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_user_groupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_user_group.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_user_groupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_user_groupAggregateArgs>(args: Prisma.Subset<T, Common_user_groupAggregateArgs>): Prisma.PrismaPromise<GetCommon_user_groupAggregateType<T>>

  /**
   * Group by Common_user_group.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_user_groupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_user_groupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_user_groupGroupByArgs['orderBy'] }
      : { orderBy?: common_user_groupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_user_groupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_user_groupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_user_group model
 */
readonly fields: common_user_groupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_user_group.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_user_groupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_user_group model
 */
export interface common_user_groupFieldRefs {
  readonly user_group_id: Prisma.FieldRef<"common_user_group", 'Int'>
  readonly user_id: Prisma.FieldRef<"common_user_group", 'String'>
  readonly group_id: Prisma.FieldRef<"common_user_group", 'Int'>
  readonly state: Prisma.FieldRef<"common_user_group", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_user_group", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_user_group", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_user_group findUnique
 */
export type common_user_groupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_user_group to fetch.
   */
  where: Prisma.common_user_groupWhereUniqueInput
}

/**
 * common_user_group findUniqueOrThrow
 */
export type common_user_groupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_user_group to fetch.
   */
  where: Prisma.common_user_groupWhereUniqueInput
}

/**
 * common_user_group findFirst
 */
export type common_user_groupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_user_group to fetch.
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_user_groups to fetch.
   */
  orderBy?: Prisma.common_user_groupOrderByWithRelationInput | Prisma.common_user_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_user_groups.
   */
  cursor?: Prisma.common_user_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_user_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_user_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_user_groups.
   */
  distinct?: Prisma.Common_user_groupScalarFieldEnum | Prisma.Common_user_groupScalarFieldEnum[]
}

/**
 * common_user_group findFirstOrThrow
 */
export type common_user_groupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_user_group to fetch.
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_user_groups to fetch.
   */
  orderBy?: Prisma.common_user_groupOrderByWithRelationInput | Prisma.common_user_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_user_groups.
   */
  cursor?: Prisma.common_user_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_user_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_user_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_user_groups.
   */
  distinct?: Prisma.Common_user_groupScalarFieldEnum | Prisma.Common_user_groupScalarFieldEnum[]
}

/**
 * common_user_group findMany
 */
export type common_user_groupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_user_groups to fetch.
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_user_groups to fetch.
   */
  orderBy?: Prisma.common_user_groupOrderByWithRelationInput | Prisma.common_user_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_user_groups.
   */
  cursor?: Prisma.common_user_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_user_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_user_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_user_groups.
   */
  distinct?: Prisma.Common_user_groupScalarFieldEnum | Prisma.Common_user_groupScalarFieldEnum[]
}

/**
 * common_user_group create
 */
export type common_user_groupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * The data needed to create a common_user_group.
   */
  data: Prisma.XOR<Prisma.common_user_groupCreateInput, Prisma.common_user_groupUncheckedCreateInput>
}

/**
 * common_user_group createMany
 */
export type common_user_groupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_user_groups.
   */
  data: Prisma.common_user_groupCreateManyInput | Prisma.common_user_groupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_user_group createManyAndReturn
 */
export type common_user_groupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * The data used to create many common_user_groups.
   */
  data: Prisma.common_user_groupCreateManyInput | Prisma.common_user_groupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_user_group update
 */
export type common_user_groupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * The data needed to update a common_user_group.
   */
  data: Prisma.XOR<Prisma.common_user_groupUpdateInput, Prisma.common_user_groupUncheckedUpdateInput>
  /**
   * Choose, which common_user_group to update.
   */
  where: Prisma.common_user_groupWhereUniqueInput
}

/**
 * common_user_group updateMany
 */
export type common_user_groupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_user_groups.
   */
  data: Prisma.XOR<Prisma.common_user_groupUpdateManyMutationInput, Prisma.common_user_groupUncheckedUpdateManyInput>
  /**
   * Filter which common_user_groups to update
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * Limit how many common_user_groups to update.
   */
  limit?: number
}

/**
 * common_user_group updateManyAndReturn
 */
export type common_user_groupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * The data used to update common_user_groups.
   */
  data: Prisma.XOR<Prisma.common_user_groupUpdateManyMutationInput, Prisma.common_user_groupUncheckedUpdateManyInput>
  /**
   * Filter which common_user_groups to update
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * Limit how many common_user_groups to update.
   */
  limit?: number
}

/**
 * common_user_group upsert
 */
export type common_user_groupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * The filter to search for the common_user_group to update in case it exists.
   */
  where: Prisma.common_user_groupWhereUniqueInput
  /**
   * In case the common_user_group found by the `where` argument doesn't exist, create a new common_user_group with this data.
   */
  create: Prisma.XOR<Prisma.common_user_groupCreateInput, Prisma.common_user_groupUncheckedCreateInput>
  /**
   * In case the common_user_group was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_user_groupUpdateInput, Prisma.common_user_groupUncheckedUpdateInput>
}

/**
 * common_user_group delete
 */
export type common_user_groupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
  /**
   * Filter which common_user_group to delete.
   */
  where: Prisma.common_user_groupWhereUniqueInput
}

/**
 * common_user_group deleteMany
 */
export type common_user_groupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_user_groups to delete
   */
  where?: Prisma.common_user_groupWhereInput
  /**
   * Limit how many common_user_groups to delete.
   */
  limit?: number
}

/**
 * common_user_group without action
 */
export type common_user_groupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user_group
   */
  select?: Prisma.common_user_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user_group
   */
  omit?: Prisma.common_user_groupOmit<ExtArgs> | null
}
