
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_user` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_user
 * 
 */
export type common_userModel = runtime.Types.Result.DefaultSelection<Prisma.$common_userPayload>

export type AggregateCommon_user = {
  _count: Common_userCountAggregateOutputType | null
  _avg: Common_userAvgAggregateOutputType | null
  _sum: Common_userSumAggregateOutputType | null
  _min: Common_userMinAggregateOutputType | null
  _max: Common_userMaxAggregateOutputType | null
}

export type Common_userAvgAggregateOutputType = {
  user_password_error: number | null
}

export type Common_userSumAggregateOutputType = {
  user_password_error: number | null
}

export type Common_userMinAggregateOutputType = {
  user_id: string | null
  user_username: string | null
  user_type: string | null
  user_email: string | null
  user_country_code: string | null
  user_phone: string | null
  user_discord: string | null
  user_telegram: string | null
  user_account: string | null
  user_password: string | null
  user_password_error: number | null
  user_login_time: Date | null
  user_name: string | null
  user_gender: string | null
  user_avatar: string | null
  user_province: string | null
  user_city: string | null
  user_district: string | null
  user_address: string | null
  user_zipcode: string | null
  user_company: string | null
  user_remark: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_userMaxAggregateOutputType = {
  user_id: string | null
  user_username: string | null
  user_type: string | null
  user_email: string | null
  user_country_code: string | null
  user_phone: string | null
  user_discord: string | null
  user_telegram: string | null
  user_account: string | null
  user_password: string | null
  user_password_error: number | null
  user_login_time: Date | null
  user_name: string | null
  user_gender: string | null
  user_avatar: string | null
  user_province: string | null
  user_city: string | null
  user_district: string | null
  user_address: string | null
  user_zipcode: string | null
  user_company: string | null
  user_remark: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_userCountAggregateOutputType = {
  user_id: number
  user_username: number
  user_type: number
  user_email: number
  user_country_code: number
  user_phone: number
  user_discord: number
  user_telegram: number
  user_account: number
  user_password: number
  user_password_error: number
  user_login_time: number
  user_name: number
  user_gender: number
  user_avatar: number
  user_province: number
  user_city: number
  user_district: number
  user_address: number
  user_zipcode: number
  user_company: number
  user_remark: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_userAvgAggregateInputType = {
  user_password_error?: true
}

export type Common_userSumAggregateInputType = {
  user_password_error?: true
}

export type Common_userMinAggregateInputType = {
  user_id?: true
  user_username?: true
  user_type?: true
  user_email?: true
  user_country_code?: true
  user_phone?: true
  user_discord?: true
  user_telegram?: true
  user_account?: true
  user_password?: true
  user_password_error?: true
  user_login_time?: true
  user_name?: true
  user_gender?: true
  user_avatar?: true
  user_province?: true
  user_city?: true
  user_district?: true
  user_address?: true
  user_zipcode?: true
  user_company?: true
  user_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_userMaxAggregateInputType = {
  user_id?: true
  user_username?: true
  user_type?: true
  user_email?: true
  user_country_code?: true
  user_phone?: true
  user_discord?: true
  user_telegram?: true
  user_account?: true
  user_password?: true
  user_password_error?: true
  user_login_time?: true
  user_name?: true
  user_gender?: true
  user_avatar?: true
  user_province?: true
  user_city?: true
  user_district?: true
  user_address?: true
  user_zipcode?: true
  user_company?: true
  user_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_userCountAggregateInputType = {
  user_id?: true
  user_username?: true
  user_type?: true
  user_email?: true
  user_country_code?: true
  user_phone?: true
  user_discord?: true
  user_telegram?: true
  user_account?: true
  user_password?: true
  user_password_error?: true
  user_login_time?: true
  user_name?: true
  user_gender?: true
  user_avatar?: true
  user_province?: true
  user_city?: true
  user_district?: true
  user_address?: true
  user_zipcode?: true
  user_company?: true
  user_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_userAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_user to aggregate.
   */
  where?: Prisma.common_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_users to fetch.
   */
  orderBy?: Prisma.common_userOrderByWithRelationInput | Prisma.common_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_users
  **/
  _count?: true | Common_userCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_userAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_userSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_userMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_userMaxAggregateInputType
}

export type GetCommon_userAggregateType<T extends Common_userAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_user]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_user[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_user[P]>
}




export type common_userGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_userWhereInput
  orderBy?: Prisma.common_userOrderByWithAggregationInput | Prisma.common_userOrderByWithAggregationInput[]
  by: Prisma.Common_userScalarFieldEnum[] | Prisma.Common_userScalarFieldEnum
  having?: Prisma.common_userScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_userCountAggregateInputType | true
  _avg?: Common_userAvgAggregateInputType
  _sum?: Common_userSumAggregateInputType
  _min?: Common_userMinAggregateInputType
  _max?: Common_userMaxAggregateInputType
}

export type Common_userGroupByOutputType = {
  user_id: string
  user_username: string
  user_type: string
  user_email: string
  user_country_code: string
  user_phone: string
  user_discord: string
  user_telegram: string
  user_account: string
  user_password: string
  user_password_error: number
  user_login_time: Date | null
  user_name: string
  user_gender: string
  user_avatar: string
  user_province: string
  user_city: string
  user_district: string
  user_address: string
  user_zipcode: string
  user_company: string
  user_remark: string
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_userCountAggregateOutputType | null
  _avg: Common_userAvgAggregateOutputType | null
  _sum: Common_userSumAggregateOutputType | null
  _min: Common_userMinAggregateOutputType | null
  _max: Common_userMaxAggregateOutputType | null
}

type GetCommon_userGroupByPayload<T extends common_userGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_userGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_userGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_userGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_userGroupByOutputType[P]>
      }
    >
  >



export type common_userWhereInput = {
  AND?: Prisma.common_userWhereInput | Prisma.common_userWhereInput[]
  OR?: Prisma.common_userWhereInput[]
  NOT?: Prisma.common_userWhereInput | Prisma.common_userWhereInput[]
  user_id?: Prisma.StringFilter<"common_user"> | string
  user_username?: Prisma.StringFilter<"common_user"> | string
  user_type?: Prisma.StringFilter<"common_user"> | string
  user_email?: Prisma.StringFilter<"common_user"> | string
  user_country_code?: Prisma.StringFilter<"common_user"> | string
  user_phone?: Prisma.StringFilter<"common_user"> | string
  user_discord?: Prisma.StringFilter<"common_user"> | string
  user_telegram?: Prisma.StringFilter<"common_user"> | string
  user_account?: Prisma.StringFilter<"common_user"> | string
  user_password?: Prisma.StringFilter<"common_user"> | string
  user_password_error?: Prisma.IntFilter<"common_user"> | number
  user_login_time?: Prisma.DateTimeNullableFilter<"common_user"> | Date | string | null
  user_name?: Prisma.StringFilter<"common_user"> | string
  user_gender?: Prisma.StringFilter<"common_user"> | string
  user_avatar?: Prisma.StringFilter<"common_user"> | string
  user_province?: Prisma.StringFilter<"common_user"> | string
  user_city?: Prisma.StringFilter<"common_user"> | string
  user_district?: Prisma.StringFilter<"common_user"> | string
  user_address?: Prisma.StringFilter<"common_user"> | string
  user_zipcode?: Prisma.StringFilter<"common_user"> | string
  user_company?: Prisma.StringFilter<"common_user"> | string
  user_remark?: Prisma.StringFilter<"common_user"> | string
  state?: Prisma.StringFilter<"common_user"> | string
  updated_at?: Prisma.DateTimeFilter<"common_user"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_user"> | Date | string
}

export type common_userOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  user_username?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  user_country_code?: Prisma.SortOrder
  user_phone?: Prisma.SortOrder
  user_discord?: Prisma.SortOrder
  user_telegram?: Prisma.SortOrder
  user_account?: Prisma.SortOrder
  user_password?: Prisma.SortOrder
  user_password_error?: Prisma.SortOrder
  user_login_time?: Prisma.SortOrderInput | Prisma.SortOrder
  user_name?: Prisma.SortOrder
  user_gender?: Prisma.SortOrder
  user_avatar?: Prisma.SortOrder
  user_province?: Prisma.SortOrder
  user_city?: Prisma.SortOrder
  user_district?: Prisma.SortOrder
  user_address?: Prisma.SortOrder
  user_zipcode?: Prisma.SortOrder
  user_company?: Prisma.SortOrder
  user_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_userWhereUniqueInput = Prisma.AtLeast<{
  user_id?: string
  AND?: Prisma.common_userWhereInput | Prisma.common_userWhereInput[]
  OR?: Prisma.common_userWhereInput[]
  NOT?: Prisma.common_userWhereInput | Prisma.common_userWhereInput[]
  user_username?: Prisma.StringFilter<"common_user"> | string
  user_type?: Prisma.StringFilter<"common_user"> | string
  user_email?: Prisma.StringFilter<"common_user"> | string
  user_country_code?: Prisma.StringFilter<"common_user"> | string
  user_phone?: Prisma.StringFilter<"common_user"> | string
  user_discord?: Prisma.StringFilter<"common_user"> | string
  user_telegram?: Prisma.StringFilter<"common_user"> | string
  user_account?: Prisma.StringFilter<"common_user"> | string
  user_password?: Prisma.StringFilter<"common_user"> | string
  user_password_error?: Prisma.IntFilter<"common_user"> | number
  user_login_time?: Prisma.DateTimeNullableFilter<"common_user"> | Date | string | null
  user_name?: Prisma.StringFilter<"common_user"> | string
  user_gender?: Prisma.StringFilter<"common_user"> | string
  user_avatar?: Prisma.StringFilter<"common_user"> | string
  user_province?: Prisma.StringFilter<"common_user"> | string
  user_city?: Prisma.StringFilter<"common_user"> | string
  user_district?: Prisma.StringFilter<"common_user"> | string
  user_address?: Prisma.StringFilter<"common_user"> | string
  user_zipcode?: Prisma.StringFilter<"common_user"> | string
  user_company?: Prisma.StringFilter<"common_user"> | string
  user_remark?: Prisma.StringFilter<"common_user"> | string
  state?: Prisma.StringFilter<"common_user"> | string
  updated_at?: Prisma.DateTimeFilter<"common_user"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_user"> | Date | string
}, "user_id">

export type common_userOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  user_username?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  user_country_code?: Prisma.SortOrder
  user_phone?: Prisma.SortOrder
  user_discord?: Prisma.SortOrder
  user_telegram?: Prisma.SortOrder
  user_account?: Prisma.SortOrder
  user_password?: Prisma.SortOrder
  user_password_error?: Prisma.SortOrder
  user_login_time?: Prisma.SortOrderInput | Prisma.SortOrder
  user_name?: Prisma.SortOrder
  user_gender?: Prisma.SortOrder
  user_avatar?: Prisma.SortOrder
  user_province?: Prisma.SortOrder
  user_city?: Prisma.SortOrder
  user_district?: Prisma.SortOrder
  user_address?: Prisma.SortOrder
  user_zipcode?: Prisma.SortOrder
  user_company?: Prisma.SortOrder
  user_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_userCountOrderByAggregateInput
  _avg?: Prisma.common_userAvgOrderByAggregateInput
  _max?: Prisma.common_userMaxOrderByAggregateInput
  _min?: Prisma.common_userMinOrderByAggregateInput
  _sum?: Prisma.common_userSumOrderByAggregateInput
}

export type common_userScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_userScalarWhereWithAggregatesInput | Prisma.common_userScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_userScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_userScalarWhereWithAggregatesInput | Prisma.common_userScalarWhereWithAggregatesInput[]
  user_id?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_username?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_type?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_email?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_country_code?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_phone?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_discord?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_telegram?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_account?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_password?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_password_error?: Prisma.IntWithAggregatesFilter<"common_user"> | number
  user_login_time?: Prisma.DateTimeNullableWithAggregatesFilter<"common_user"> | Date | string | null
  user_name?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_gender?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_avatar?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_province?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_city?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_district?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_address?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_zipcode?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_company?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  user_remark?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  state?: Prisma.StringWithAggregatesFilter<"common_user"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_user"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_user"> | Date | string
}

export type common_userCreateInput = {
  user_id?: string
  user_username?: string
  user_type: string
  user_email?: string
  user_country_code?: string
  user_phone?: string
  user_discord?: string
  user_telegram?: string
  user_account?: string
  user_password: string
  user_password_error?: number
  user_login_time?: Date | string | null
  user_name?: string
  user_gender?: string
  user_avatar?: string
  user_province?: string
  user_city?: string
  user_district?: string
  user_address?: string
  user_zipcode?: string
  user_company?: string
  user_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_userUncheckedCreateInput = {
  user_id?: string
  user_username?: string
  user_type: string
  user_email?: string
  user_country_code?: string
  user_phone?: string
  user_discord?: string
  user_telegram?: string
  user_account?: string
  user_password: string
  user_password_error?: number
  user_login_time?: Date | string | null
  user_name?: string
  user_gender?: string
  user_avatar?: string
  user_province?: string
  user_city?: string
  user_district?: string
  user_address?: string
  user_zipcode?: string
  user_company?: string
  user_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_userUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_username?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  user_country_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_phone?: Prisma.StringFieldUpdateOperationsInput | string
  user_discord?: Prisma.StringFieldUpdateOperationsInput | string
  user_telegram?: Prisma.StringFieldUpdateOperationsInput | string
  user_account?: Prisma.StringFieldUpdateOperationsInput | string
  user_password?: Prisma.StringFieldUpdateOperationsInput | string
  user_password_error?: Prisma.IntFieldUpdateOperationsInput | number
  user_login_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_gender?: Prisma.StringFieldUpdateOperationsInput | string
  user_avatar?: Prisma.StringFieldUpdateOperationsInput | string
  user_province?: Prisma.StringFieldUpdateOperationsInput | string
  user_city?: Prisma.StringFieldUpdateOperationsInput | string
  user_district?: Prisma.StringFieldUpdateOperationsInput | string
  user_address?: Prisma.StringFieldUpdateOperationsInput | string
  user_zipcode?: Prisma.StringFieldUpdateOperationsInput | string
  user_company?: Prisma.StringFieldUpdateOperationsInput | string
  user_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_userUncheckedUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_username?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  user_country_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_phone?: Prisma.StringFieldUpdateOperationsInput | string
  user_discord?: Prisma.StringFieldUpdateOperationsInput | string
  user_telegram?: Prisma.StringFieldUpdateOperationsInput | string
  user_account?: Prisma.StringFieldUpdateOperationsInput | string
  user_password?: Prisma.StringFieldUpdateOperationsInput | string
  user_password_error?: Prisma.IntFieldUpdateOperationsInput | number
  user_login_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_gender?: Prisma.StringFieldUpdateOperationsInput | string
  user_avatar?: Prisma.StringFieldUpdateOperationsInput | string
  user_province?: Prisma.StringFieldUpdateOperationsInput | string
  user_city?: Prisma.StringFieldUpdateOperationsInput | string
  user_district?: Prisma.StringFieldUpdateOperationsInput | string
  user_address?: Prisma.StringFieldUpdateOperationsInput | string
  user_zipcode?: Prisma.StringFieldUpdateOperationsInput | string
  user_company?: Prisma.StringFieldUpdateOperationsInput | string
  user_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_userCreateManyInput = {
  user_id?: string
  user_username?: string
  user_type: string
  user_email?: string
  user_country_code?: string
  user_phone?: string
  user_discord?: string
  user_telegram?: string
  user_account?: string
  user_password: string
  user_password_error?: number
  user_login_time?: Date | string | null
  user_name?: string
  user_gender?: string
  user_avatar?: string
  user_province?: string
  user_city?: string
  user_district?: string
  user_address?: string
  user_zipcode?: string
  user_company?: string
  user_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_userUpdateManyMutationInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_username?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  user_country_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_phone?: Prisma.StringFieldUpdateOperationsInput | string
  user_discord?: Prisma.StringFieldUpdateOperationsInput | string
  user_telegram?: Prisma.StringFieldUpdateOperationsInput | string
  user_account?: Prisma.StringFieldUpdateOperationsInput | string
  user_password?: Prisma.StringFieldUpdateOperationsInput | string
  user_password_error?: Prisma.IntFieldUpdateOperationsInput | number
  user_login_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_gender?: Prisma.StringFieldUpdateOperationsInput | string
  user_avatar?: Prisma.StringFieldUpdateOperationsInput | string
  user_province?: Prisma.StringFieldUpdateOperationsInput | string
  user_city?: Prisma.StringFieldUpdateOperationsInput | string
  user_district?: Prisma.StringFieldUpdateOperationsInput | string
  user_address?: Prisma.StringFieldUpdateOperationsInput | string
  user_zipcode?: Prisma.StringFieldUpdateOperationsInput | string
  user_company?: Prisma.StringFieldUpdateOperationsInput | string
  user_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_userUncheckedUpdateManyInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_username?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  user_email?: Prisma.StringFieldUpdateOperationsInput | string
  user_country_code?: Prisma.StringFieldUpdateOperationsInput | string
  user_phone?: Prisma.StringFieldUpdateOperationsInput | string
  user_discord?: Prisma.StringFieldUpdateOperationsInput | string
  user_telegram?: Prisma.StringFieldUpdateOperationsInput | string
  user_account?: Prisma.StringFieldUpdateOperationsInput | string
  user_password?: Prisma.StringFieldUpdateOperationsInput | string
  user_password_error?: Prisma.IntFieldUpdateOperationsInput | number
  user_login_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_name?: Prisma.StringFieldUpdateOperationsInput | string
  user_gender?: Prisma.StringFieldUpdateOperationsInput | string
  user_avatar?: Prisma.StringFieldUpdateOperationsInput | string
  user_province?: Prisma.StringFieldUpdateOperationsInput | string
  user_city?: Prisma.StringFieldUpdateOperationsInput | string
  user_district?: Prisma.StringFieldUpdateOperationsInput | string
  user_address?: Prisma.StringFieldUpdateOperationsInput | string
  user_zipcode?: Prisma.StringFieldUpdateOperationsInput | string
  user_company?: Prisma.StringFieldUpdateOperationsInput | string
  user_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_userCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  user_username?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  user_country_code?: Prisma.SortOrder
  user_phone?: Prisma.SortOrder
  user_discord?: Prisma.SortOrder
  user_telegram?: Prisma.SortOrder
  user_account?: Prisma.SortOrder
  user_password?: Prisma.SortOrder
  user_password_error?: Prisma.SortOrder
  user_login_time?: Prisma.SortOrder
  user_name?: Prisma.SortOrder
  user_gender?: Prisma.SortOrder
  user_avatar?: Prisma.SortOrder
  user_province?: Prisma.SortOrder
  user_city?: Prisma.SortOrder
  user_district?: Prisma.SortOrder
  user_address?: Prisma.SortOrder
  user_zipcode?: Prisma.SortOrder
  user_company?: Prisma.SortOrder
  user_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_userAvgOrderByAggregateInput = {
  user_password_error?: Prisma.SortOrder
}

export type common_userMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  user_username?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  user_country_code?: Prisma.SortOrder
  user_phone?: Prisma.SortOrder
  user_discord?: Prisma.SortOrder
  user_telegram?: Prisma.SortOrder
  user_account?: Prisma.SortOrder
  user_password?: Prisma.SortOrder
  user_password_error?: Prisma.SortOrder
  user_login_time?: Prisma.SortOrder
  user_name?: Prisma.SortOrder
  user_gender?: Prisma.SortOrder
  user_avatar?: Prisma.SortOrder
  user_province?: Prisma.SortOrder
  user_city?: Prisma.SortOrder
  user_district?: Prisma.SortOrder
  user_address?: Prisma.SortOrder
  user_zipcode?: Prisma.SortOrder
  user_company?: Prisma.SortOrder
  user_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_userMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  user_username?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  user_email?: Prisma.SortOrder
  user_country_code?: Prisma.SortOrder
  user_phone?: Prisma.SortOrder
  user_discord?: Prisma.SortOrder
  user_telegram?: Prisma.SortOrder
  user_account?: Prisma.SortOrder
  user_password?: Prisma.SortOrder
  user_password_error?: Prisma.SortOrder
  user_login_time?: Prisma.SortOrder
  user_name?: Prisma.SortOrder
  user_gender?: Prisma.SortOrder
  user_avatar?: Prisma.SortOrder
  user_province?: Prisma.SortOrder
  user_city?: Prisma.SortOrder
  user_district?: Prisma.SortOrder
  user_address?: Prisma.SortOrder
  user_zipcode?: Prisma.SortOrder
  user_company?: Prisma.SortOrder
  user_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_userSumOrderByAggregateInput = {
  user_password_error?: Prisma.SortOrder
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type common_userSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  user_username?: boolean
  user_type?: boolean
  user_email?: boolean
  user_country_code?: boolean
  user_phone?: boolean
  user_discord?: boolean
  user_telegram?: boolean
  user_account?: boolean
  user_password?: boolean
  user_password_error?: boolean
  user_login_time?: boolean
  user_name?: boolean
  user_gender?: boolean
  user_avatar?: boolean
  user_province?: boolean
  user_city?: boolean
  user_district?: boolean
  user_address?: boolean
  user_zipcode?: boolean
  user_company?: boolean
  user_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user"]>

export type common_userSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  user_username?: boolean
  user_type?: boolean
  user_email?: boolean
  user_country_code?: boolean
  user_phone?: boolean
  user_discord?: boolean
  user_telegram?: boolean
  user_account?: boolean
  user_password?: boolean
  user_password_error?: boolean
  user_login_time?: boolean
  user_name?: boolean
  user_gender?: boolean
  user_avatar?: boolean
  user_province?: boolean
  user_city?: boolean
  user_district?: boolean
  user_address?: boolean
  user_zipcode?: boolean
  user_company?: boolean
  user_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user"]>

export type common_userSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  user_username?: boolean
  user_type?: boolean
  user_email?: boolean
  user_country_code?: boolean
  user_phone?: boolean
  user_discord?: boolean
  user_telegram?: boolean
  user_account?: boolean
  user_password?: boolean
  user_password_error?: boolean
  user_login_time?: boolean
  user_name?: boolean
  user_gender?: boolean
  user_avatar?: boolean
  user_province?: boolean
  user_city?: boolean
  user_district?: boolean
  user_address?: boolean
  user_zipcode?: boolean
  user_company?: boolean
  user_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_user"]>

export type common_userSelectScalar = {
  user_id?: boolean
  user_username?: boolean
  user_type?: boolean
  user_email?: boolean
  user_country_code?: boolean
  user_phone?: boolean
  user_discord?: boolean
  user_telegram?: boolean
  user_account?: boolean
  user_password?: boolean
  user_password_error?: boolean
  user_login_time?: boolean
  user_name?: boolean
  user_gender?: boolean
  user_avatar?: boolean
  user_province?: boolean
  user_city?: boolean
  user_district?: boolean
  user_address?: boolean
  user_zipcode?: boolean
  user_company?: boolean
  user_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_userOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "user_username" | "user_type" | "user_email" | "user_country_code" | "user_phone" | "user_discord" | "user_telegram" | "user_account" | "user_password" | "user_password_error" | "user_login_time" | "user_name" | "user_gender" | "user_avatar" | "user_province" | "user_city" | "user_district" | "user_address" | "user_zipcode" | "user_company" | "user_remark" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_user"]>

export type $common_userPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_user"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: string
    user_username: string
    user_type: string
    user_email: string
    user_country_code: string
    user_phone: string
    user_discord: string
    user_telegram: string
    user_account: string
    user_password: string
    user_password_error: number
    user_login_time: Date | null
    user_name: string
    user_gender: string
    user_avatar: string
    user_province: string
    user_city: string
    user_district: string
    user_address: string
    user_zipcode: string
    user_company: string
    user_remark: string
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_user"]>
  composites: {}
}

export type common_userGetPayload<S extends boolean | null | undefined | common_userDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_userPayload, S>

export type common_userCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_userFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_userCountAggregateInputType | true
  }

export interface common_userDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_user'], meta: { name: 'common_user' } }
  /**
   * Find zero or one Common_user that matches the filter.
   * @param {common_userFindUniqueArgs} args - Arguments to find a Common_user
   * @example
   * // Get one Common_user
   * const common_user = await prisma.common_user.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_userFindUniqueArgs>(args: Prisma.SelectSubset<T, common_userFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_user that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_userFindUniqueOrThrowArgs} args - Arguments to find a Common_user
   * @example
   * // Get one Common_user
   * const common_user = await prisma.common_user.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_userFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_userFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_user that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userFindFirstArgs} args - Arguments to find a Common_user
   * @example
   * // Get one Common_user
   * const common_user = await prisma.common_user.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_userFindFirstArgs>(args?: Prisma.SelectSubset<T, common_userFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_user that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userFindFirstOrThrowArgs} args - Arguments to find a Common_user
   * @example
   * // Get one Common_user
   * const common_user = await prisma.common_user.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_userFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_userFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_users that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_users
   * const common_users = await prisma.common_user.findMany()
   * 
   * // Get first 10 Common_users
   * const common_users = await prisma.common_user.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const common_userWithUser_idOnly = await prisma.common_user.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends common_userFindManyArgs>(args?: Prisma.SelectSubset<T, common_userFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_user.
   * @param {common_userCreateArgs} args - Arguments to create a Common_user.
   * @example
   * // Create one Common_user
   * const Common_user = await prisma.common_user.create({
   *   data: {
   *     // ... data to create a Common_user
   *   }
   * })
   * 
   */
  create<T extends common_userCreateArgs>(args: Prisma.SelectSubset<T, common_userCreateArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_users.
   * @param {common_userCreateManyArgs} args - Arguments to create many Common_users.
   * @example
   * // Create many Common_users
   * const common_user = await prisma.common_user.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_userCreateManyArgs>(args?: Prisma.SelectSubset<T, common_userCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_users and returns the data saved in the database.
   * @param {common_userCreateManyAndReturnArgs} args - Arguments to create many Common_users.
   * @example
   * // Create many Common_users
   * const common_user = await prisma.common_user.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_users and only return the `user_id`
   * const common_userWithUser_idOnly = await prisma.common_user.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_userCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_userCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_user.
   * @param {common_userDeleteArgs} args - Arguments to delete one Common_user.
   * @example
   * // Delete one Common_user
   * const Common_user = await prisma.common_user.delete({
   *   where: {
   *     // ... filter to delete one Common_user
   *   }
   * })
   * 
   */
  delete<T extends common_userDeleteArgs>(args: Prisma.SelectSubset<T, common_userDeleteArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_user.
   * @param {common_userUpdateArgs} args - Arguments to update one Common_user.
   * @example
   * // Update one Common_user
   * const common_user = await prisma.common_user.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_userUpdateArgs>(args: Prisma.SelectSubset<T, common_userUpdateArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_users.
   * @param {common_userDeleteManyArgs} args - Arguments to filter Common_users to delete.
   * @example
   * // Delete a few Common_users
   * const { count } = await prisma.common_user.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_userDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_userDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_users
   * const common_user = await prisma.common_user.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_userUpdateManyArgs>(args: Prisma.SelectSubset<T, common_userUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_users and returns the data updated in the database.
   * @param {common_userUpdateManyAndReturnArgs} args - Arguments to update many Common_users.
   * @example
   * // Update many Common_users
   * const common_user = await prisma.common_user.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_users and only return the `user_id`
   * const common_userWithUser_idOnly = await prisma.common_user.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_userUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_userUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_user.
   * @param {common_userUpsertArgs} args - Arguments to update or create a Common_user.
   * @example
   * // Update or create a Common_user
   * const common_user = await prisma.common_user.upsert({
   *   create: {
   *     // ... data to create a Common_user
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_user we want to update
   *   }
   * })
   */
  upsert<T extends common_userUpsertArgs>(args: Prisma.SelectSubset<T, common_userUpsertArgs<ExtArgs>>): Prisma.Prisma__common_userClient<runtime.Types.Result.GetResult<Prisma.$common_userPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_users.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userCountArgs} args - Arguments to filter Common_users to count.
   * @example
   * // Count the number of Common_users
   * const count = await prisma.common_user.count({
   *   where: {
   *     // ... the filter for the Common_users we want to count
   *   }
   * })
  **/
  count<T extends common_userCountArgs>(
    args?: Prisma.Subset<T, common_userCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_userCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_userAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_userAggregateArgs>(args: Prisma.Subset<T, Common_userAggregateArgs>): Prisma.PrismaPromise<GetCommon_userAggregateType<T>>

  /**
   * Group by Common_user.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_userGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_userGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_userGroupByArgs['orderBy'] }
      : { orderBy?: common_userGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_userGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_userGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_user model
 */
readonly fields: common_userFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_user.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_userClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_user model
 */
export interface common_userFieldRefs {
  readonly user_id: Prisma.FieldRef<"common_user", 'String'>
  readonly user_username: Prisma.FieldRef<"common_user", 'String'>
  readonly user_type: Prisma.FieldRef<"common_user", 'String'>
  readonly user_email: Prisma.FieldRef<"common_user", 'String'>
  readonly user_country_code: Prisma.FieldRef<"common_user", 'String'>
  readonly user_phone: Prisma.FieldRef<"common_user", 'String'>
  readonly user_discord: Prisma.FieldRef<"common_user", 'String'>
  readonly user_telegram: Prisma.FieldRef<"common_user", 'String'>
  readonly user_account: Prisma.FieldRef<"common_user", 'String'>
  readonly user_password: Prisma.FieldRef<"common_user", 'String'>
  readonly user_password_error: Prisma.FieldRef<"common_user", 'Int'>
  readonly user_login_time: Prisma.FieldRef<"common_user", 'DateTime'>
  readonly user_name: Prisma.FieldRef<"common_user", 'String'>
  readonly user_gender: Prisma.FieldRef<"common_user", 'String'>
  readonly user_avatar: Prisma.FieldRef<"common_user", 'String'>
  readonly user_province: Prisma.FieldRef<"common_user", 'String'>
  readonly user_city: Prisma.FieldRef<"common_user", 'String'>
  readonly user_district: Prisma.FieldRef<"common_user", 'String'>
  readonly user_address: Prisma.FieldRef<"common_user", 'String'>
  readonly user_zipcode: Prisma.FieldRef<"common_user", 'String'>
  readonly user_company: Prisma.FieldRef<"common_user", 'String'>
  readonly user_remark: Prisma.FieldRef<"common_user", 'String'>
  readonly state: Prisma.FieldRef<"common_user", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_user", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_user", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_user findUnique
 */
export type common_userFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter, which common_user to fetch.
   */
  where: Prisma.common_userWhereUniqueInput
}

/**
 * common_user findUniqueOrThrow
 */
export type common_userFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter, which common_user to fetch.
   */
  where: Prisma.common_userWhereUniqueInput
}

/**
 * common_user findFirst
 */
export type common_userFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter, which common_user to fetch.
   */
  where?: Prisma.common_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_users to fetch.
   */
  orderBy?: Prisma.common_userOrderByWithRelationInput | Prisma.common_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_users.
   */
  cursor?: Prisma.common_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_users.
   */
  distinct?: Prisma.Common_userScalarFieldEnum | Prisma.Common_userScalarFieldEnum[]
}

/**
 * common_user findFirstOrThrow
 */
export type common_userFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter, which common_user to fetch.
   */
  where?: Prisma.common_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_users to fetch.
   */
  orderBy?: Prisma.common_userOrderByWithRelationInput | Prisma.common_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_users.
   */
  cursor?: Prisma.common_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_users.
   */
  distinct?: Prisma.Common_userScalarFieldEnum | Prisma.Common_userScalarFieldEnum[]
}

/**
 * common_user findMany
 */
export type common_userFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter, which common_users to fetch.
   */
  where?: Prisma.common_userWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_users to fetch.
   */
  orderBy?: Prisma.common_userOrderByWithRelationInput | Prisma.common_userOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_users.
   */
  cursor?: Prisma.common_userWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_users from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_users.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_users.
   */
  distinct?: Prisma.Common_userScalarFieldEnum | Prisma.Common_userScalarFieldEnum[]
}

/**
 * common_user create
 */
export type common_userCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * The data needed to create a common_user.
   */
  data: Prisma.XOR<Prisma.common_userCreateInput, Prisma.common_userUncheckedCreateInput>
}

/**
 * common_user createMany
 */
export type common_userCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_users.
   */
  data: Prisma.common_userCreateManyInput | Prisma.common_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_user createManyAndReturn
 */
export type common_userCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * The data used to create many common_users.
   */
  data: Prisma.common_userCreateManyInput | Prisma.common_userCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_user update
 */
export type common_userUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * The data needed to update a common_user.
   */
  data: Prisma.XOR<Prisma.common_userUpdateInput, Prisma.common_userUncheckedUpdateInput>
  /**
   * Choose, which common_user to update.
   */
  where: Prisma.common_userWhereUniqueInput
}

/**
 * common_user updateMany
 */
export type common_userUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_users.
   */
  data: Prisma.XOR<Prisma.common_userUpdateManyMutationInput, Prisma.common_userUncheckedUpdateManyInput>
  /**
   * Filter which common_users to update
   */
  where?: Prisma.common_userWhereInput
  /**
   * Limit how many common_users to update.
   */
  limit?: number
}

/**
 * common_user updateManyAndReturn
 */
export type common_userUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * The data used to update common_users.
   */
  data: Prisma.XOR<Prisma.common_userUpdateManyMutationInput, Prisma.common_userUncheckedUpdateManyInput>
  /**
   * Filter which common_users to update
   */
  where?: Prisma.common_userWhereInput
  /**
   * Limit how many common_users to update.
   */
  limit?: number
}

/**
 * common_user upsert
 */
export type common_userUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * The filter to search for the common_user to update in case it exists.
   */
  where: Prisma.common_userWhereUniqueInput
  /**
   * In case the common_user found by the `where` argument doesn't exist, create a new common_user with this data.
   */
  create: Prisma.XOR<Prisma.common_userCreateInput, Prisma.common_userUncheckedCreateInput>
  /**
   * In case the common_user was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_userUpdateInput, Prisma.common_userUncheckedUpdateInput>
}

/**
 * common_user delete
 */
export type common_userDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
  /**
   * Filter which common_user to delete.
   */
  where: Prisma.common_userWhereUniqueInput
}

/**
 * common_user deleteMany
 */
export type common_userDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_users to delete
   */
  where?: Prisma.common_userWhereInput
  /**
   * Limit how many common_users to delete.
   */
  limit?: number
}

/**
 * common_user without action
 */
export type common_userDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_user
   */
  select?: Prisma.common_userSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_user
   */
  omit?: Prisma.common_userOmit<ExtArgs> | null
}
