
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_api` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_api
 * 
 */
export type common_apiModel = runtime.Types.Result.DefaultSelection<Prisma.$common_apiPayload>

export type AggregateCommon_api = {
  _count: Common_apiCountAggregateOutputType | null
  _avg: Common_apiAvgAggregateOutputType | null
  _sum: Common_apiSumAggregateOutputType | null
  _min: Common_apiMinAggregateOutputType | null
  _max: Common_apiMaxAggregateOutputType | null
}

export type Common_apiAvgAggregateOutputType = {
  api_id: number | null
}

export type Common_apiSumAggregateOutputType = {
  api_id: number | null
}

export type Common_apiMinAggregateOutputType = {
  api_id: number | null
  api_type: string | null
  api_name: string | null
  api_path: string | null
  api_function: string | null
  auth_flag: string | null
  api_remark: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_apiMaxAggregateOutputType = {
  api_id: number | null
  api_type: string | null
  api_name: string | null
  api_path: string | null
  api_function: string | null
  auth_flag: string | null
  api_remark: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_apiCountAggregateOutputType = {
  api_id: number
  api_type: number
  api_name: number
  api_path: number
  api_function: number
  auth_flag: number
  api_remark: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_apiAvgAggregateInputType = {
  api_id?: true
}

export type Common_apiSumAggregateInputType = {
  api_id?: true
}

export type Common_apiMinAggregateInputType = {
  api_id?: true
  api_type?: true
  api_name?: true
  api_path?: true
  api_function?: true
  auth_flag?: true
  api_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_apiMaxAggregateInputType = {
  api_id?: true
  api_type?: true
  api_name?: true
  api_path?: true
  api_function?: true
  auth_flag?: true
  api_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_apiCountAggregateInputType = {
  api_id?: true
  api_type?: true
  api_name?: true
  api_path?: true
  api_function?: true
  auth_flag?: true
  api_remark?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_apiAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_api to aggregate.
   */
  where?: Prisma.common_apiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_apis to fetch.
   */
  orderBy?: Prisma.common_apiOrderByWithRelationInput | Prisma.common_apiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_apiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_apis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_apis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_apis
  **/
  _count?: true | Common_apiCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_apiAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_apiSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_apiMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_apiMaxAggregateInputType
}

export type GetCommon_apiAggregateType<T extends Common_apiAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_api]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_api[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_api[P]>
}




export type common_apiGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_apiWhereInput
  orderBy?: Prisma.common_apiOrderByWithAggregationInput | Prisma.common_apiOrderByWithAggregationInput[]
  by: Prisma.Common_apiScalarFieldEnum[] | Prisma.Common_apiScalarFieldEnum
  having?: Prisma.common_apiScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_apiCountAggregateInputType | true
  _avg?: Common_apiAvgAggregateInputType
  _sum?: Common_apiSumAggregateInputType
  _min?: Common_apiMinAggregateInputType
  _max?: Common_apiMaxAggregateInputType
}

export type Common_apiGroupByOutputType = {
  api_id: number
  api_type: string
  api_name: string
  api_path: string
  api_function: string
  auth_flag: string
  api_remark: string
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_apiCountAggregateOutputType | null
  _avg: Common_apiAvgAggregateOutputType | null
  _sum: Common_apiSumAggregateOutputType | null
  _min: Common_apiMinAggregateOutputType | null
  _max: Common_apiMaxAggregateOutputType | null
}

type GetCommon_apiGroupByPayload<T extends common_apiGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_apiGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_apiGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_apiGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_apiGroupByOutputType[P]>
      }
    >
  >



export type common_apiWhereInput = {
  AND?: Prisma.common_apiWhereInput | Prisma.common_apiWhereInput[]
  OR?: Prisma.common_apiWhereInput[]
  NOT?: Prisma.common_apiWhereInput | Prisma.common_apiWhereInput[]
  api_id?: Prisma.IntFilter<"common_api"> | number
  api_type?: Prisma.StringFilter<"common_api"> | string
  api_name?: Prisma.StringFilter<"common_api"> | string
  api_path?: Prisma.StringFilter<"common_api"> | string
  api_function?: Prisma.StringFilter<"common_api"> | string
  auth_flag?: Prisma.StringFilter<"common_api"> | string
  api_remark?: Prisma.StringFilter<"common_api"> | string
  state?: Prisma.StringFilter<"common_api"> | string
  updated_at?: Prisma.DateTimeFilter<"common_api"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_api"> | Date | string
}

export type common_apiOrderByWithRelationInput = {
  api_id?: Prisma.SortOrder
  api_type?: Prisma.SortOrder
  api_name?: Prisma.SortOrder
  api_path?: Prisma.SortOrder
  api_function?: Prisma.SortOrder
  auth_flag?: Prisma.SortOrder
  api_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_apiWhereUniqueInput = Prisma.AtLeast<{
  api_id?: number
  AND?: Prisma.common_apiWhereInput | Prisma.common_apiWhereInput[]
  OR?: Prisma.common_apiWhereInput[]
  NOT?: Prisma.common_apiWhereInput | Prisma.common_apiWhereInput[]
  api_type?: Prisma.StringFilter<"common_api"> | string
  api_name?: Prisma.StringFilter<"common_api"> | string
  api_path?: Prisma.StringFilter<"common_api"> | string
  api_function?: Prisma.StringFilter<"common_api"> | string
  auth_flag?: Prisma.StringFilter<"common_api"> | string
  api_remark?: Prisma.StringFilter<"common_api"> | string
  state?: Prisma.StringFilter<"common_api"> | string
  updated_at?: Prisma.DateTimeFilter<"common_api"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_api"> | Date | string
}, "api_id">

export type common_apiOrderByWithAggregationInput = {
  api_id?: Prisma.SortOrder
  api_type?: Prisma.SortOrder
  api_name?: Prisma.SortOrder
  api_path?: Prisma.SortOrder
  api_function?: Prisma.SortOrder
  auth_flag?: Prisma.SortOrder
  api_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_apiCountOrderByAggregateInput
  _avg?: Prisma.common_apiAvgOrderByAggregateInput
  _max?: Prisma.common_apiMaxOrderByAggregateInput
  _min?: Prisma.common_apiMinOrderByAggregateInput
  _sum?: Prisma.common_apiSumOrderByAggregateInput
}

export type common_apiScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_apiScalarWhereWithAggregatesInput | Prisma.common_apiScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_apiScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_apiScalarWhereWithAggregatesInput | Prisma.common_apiScalarWhereWithAggregatesInput[]
  api_id?: Prisma.IntWithAggregatesFilter<"common_api"> | number
  api_type?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  api_name?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  api_path?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  api_function?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  auth_flag?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  api_remark?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  state?: Prisma.StringWithAggregatesFilter<"common_api"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_api"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_api"> | Date | string
}

export type common_apiCreateInput = {
  api_type?: string
  api_name?: string
  api_path?: string
  api_function?: string
  auth_flag?: string
  api_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_apiUncheckedCreateInput = {
  api_id?: number
  api_type?: string
  api_name?: string
  api_path?: string
  api_function?: string
  auth_flag?: string
  api_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_apiUpdateInput = {
  api_type?: Prisma.StringFieldUpdateOperationsInput | string
  api_name?: Prisma.StringFieldUpdateOperationsInput | string
  api_path?: Prisma.StringFieldUpdateOperationsInput | string
  api_function?: Prisma.StringFieldUpdateOperationsInput | string
  auth_flag?: Prisma.StringFieldUpdateOperationsInput | string
  api_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_apiUncheckedUpdateInput = {
  api_id?: Prisma.IntFieldUpdateOperationsInput | number
  api_type?: Prisma.StringFieldUpdateOperationsInput | string
  api_name?: Prisma.StringFieldUpdateOperationsInput | string
  api_path?: Prisma.StringFieldUpdateOperationsInput | string
  api_function?: Prisma.StringFieldUpdateOperationsInput | string
  auth_flag?: Prisma.StringFieldUpdateOperationsInput | string
  api_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_apiCreateManyInput = {
  api_id?: number
  api_type?: string
  api_name?: string
  api_path?: string
  api_function?: string
  auth_flag?: string
  api_remark?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_apiUpdateManyMutationInput = {
  api_type?: Prisma.StringFieldUpdateOperationsInput | string
  api_name?: Prisma.StringFieldUpdateOperationsInput | string
  api_path?: Prisma.StringFieldUpdateOperationsInput | string
  api_function?: Prisma.StringFieldUpdateOperationsInput | string
  auth_flag?: Prisma.StringFieldUpdateOperationsInput | string
  api_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_apiUncheckedUpdateManyInput = {
  api_id?: Prisma.IntFieldUpdateOperationsInput | number
  api_type?: Prisma.StringFieldUpdateOperationsInput | string
  api_name?: Prisma.StringFieldUpdateOperationsInput | string
  api_path?: Prisma.StringFieldUpdateOperationsInput | string
  api_function?: Prisma.StringFieldUpdateOperationsInput | string
  auth_flag?: Prisma.StringFieldUpdateOperationsInput | string
  api_remark?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_apiCountOrderByAggregateInput = {
  api_id?: Prisma.SortOrder
  api_type?: Prisma.SortOrder
  api_name?: Prisma.SortOrder
  api_path?: Prisma.SortOrder
  api_function?: Prisma.SortOrder
  auth_flag?: Prisma.SortOrder
  api_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_apiAvgOrderByAggregateInput = {
  api_id?: Prisma.SortOrder
}

export type common_apiMaxOrderByAggregateInput = {
  api_id?: Prisma.SortOrder
  api_type?: Prisma.SortOrder
  api_name?: Prisma.SortOrder
  api_path?: Prisma.SortOrder
  api_function?: Prisma.SortOrder
  auth_flag?: Prisma.SortOrder
  api_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_apiMinOrderByAggregateInput = {
  api_id?: Prisma.SortOrder
  api_type?: Prisma.SortOrder
  api_name?: Prisma.SortOrder
  api_path?: Prisma.SortOrder
  api_function?: Prisma.SortOrder
  auth_flag?: Prisma.SortOrder
  api_remark?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_apiSumOrderByAggregateInput = {
  api_id?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type common_apiSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  api_id?: boolean
  api_type?: boolean
  api_name?: boolean
  api_path?: boolean
  api_function?: boolean
  auth_flag?: boolean
  api_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_api"]>

export type common_apiSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  api_id?: boolean
  api_type?: boolean
  api_name?: boolean
  api_path?: boolean
  api_function?: boolean
  auth_flag?: boolean
  api_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_api"]>

export type common_apiSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  api_id?: boolean
  api_type?: boolean
  api_name?: boolean
  api_path?: boolean
  api_function?: boolean
  auth_flag?: boolean
  api_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_api"]>

export type common_apiSelectScalar = {
  api_id?: boolean
  api_type?: boolean
  api_name?: boolean
  api_path?: boolean
  api_function?: boolean
  auth_flag?: boolean
  api_remark?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_apiOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"api_id" | "api_type" | "api_name" | "api_path" | "api_function" | "auth_flag" | "api_remark" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_api"]>

export type $common_apiPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_api"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    api_id: number
    api_type: string
    api_name: string
    api_path: string
    api_function: string
    auth_flag: string
    api_remark: string
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_api"]>
  composites: {}
}

export type common_apiGetPayload<S extends boolean | null | undefined | common_apiDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_apiPayload, S>

export type common_apiCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_apiFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_apiCountAggregateInputType | true
  }

export interface common_apiDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_api'], meta: { name: 'common_api' } }
  /**
   * Find zero or one Common_api that matches the filter.
   * @param {common_apiFindUniqueArgs} args - Arguments to find a Common_api
   * @example
   * // Get one Common_api
   * const common_api = await prisma.common_api.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_apiFindUniqueArgs>(args: Prisma.SelectSubset<T, common_apiFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_api that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_apiFindUniqueOrThrowArgs} args - Arguments to find a Common_api
   * @example
   * // Get one Common_api
   * const common_api = await prisma.common_api.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_apiFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_apiFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_api that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiFindFirstArgs} args - Arguments to find a Common_api
   * @example
   * // Get one Common_api
   * const common_api = await prisma.common_api.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_apiFindFirstArgs>(args?: Prisma.SelectSubset<T, common_apiFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_api that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiFindFirstOrThrowArgs} args - Arguments to find a Common_api
   * @example
   * // Get one Common_api
   * const common_api = await prisma.common_api.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_apiFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_apiFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_apis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_apis
   * const common_apis = await prisma.common_api.findMany()
   * 
   * // Get first 10 Common_apis
   * const common_apis = await prisma.common_api.findMany({ take: 10 })
   * 
   * // Only select the `api_id`
   * const common_apiWithApi_idOnly = await prisma.common_api.findMany({ select: { api_id: true } })
   * 
   */
  findMany<T extends common_apiFindManyArgs>(args?: Prisma.SelectSubset<T, common_apiFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_api.
   * @param {common_apiCreateArgs} args - Arguments to create a Common_api.
   * @example
   * // Create one Common_api
   * const Common_api = await prisma.common_api.create({
   *   data: {
   *     // ... data to create a Common_api
   *   }
   * })
   * 
   */
  create<T extends common_apiCreateArgs>(args: Prisma.SelectSubset<T, common_apiCreateArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_apis.
   * @param {common_apiCreateManyArgs} args - Arguments to create many Common_apis.
   * @example
   * // Create many Common_apis
   * const common_api = await prisma.common_api.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_apiCreateManyArgs>(args?: Prisma.SelectSubset<T, common_apiCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_apis and returns the data saved in the database.
   * @param {common_apiCreateManyAndReturnArgs} args - Arguments to create many Common_apis.
   * @example
   * // Create many Common_apis
   * const common_api = await prisma.common_api.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_apis and only return the `api_id`
   * const common_apiWithApi_idOnly = await prisma.common_api.createManyAndReturn({
   *   select: { api_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_apiCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_apiCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_api.
   * @param {common_apiDeleteArgs} args - Arguments to delete one Common_api.
   * @example
   * // Delete one Common_api
   * const Common_api = await prisma.common_api.delete({
   *   where: {
   *     // ... filter to delete one Common_api
   *   }
   * })
   * 
   */
  delete<T extends common_apiDeleteArgs>(args: Prisma.SelectSubset<T, common_apiDeleteArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_api.
   * @param {common_apiUpdateArgs} args - Arguments to update one Common_api.
   * @example
   * // Update one Common_api
   * const common_api = await prisma.common_api.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_apiUpdateArgs>(args: Prisma.SelectSubset<T, common_apiUpdateArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_apis.
   * @param {common_apiDeleteManyArgs} args - Arguments to filter Common_apis to delete.
   * @example
   * // Delete a few Common_apis
   * const { count } = await prisma.common_api.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_apiDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_apiDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_apis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_apis
   * const common_api = await prisma.common_api.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_apiUpdateManyArgs>(args: Prisma.SelectSubset<T, common_apiUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_apis and returns the data updated in the database.
   * @param {common_apiUpdateManyAndReturnArgs} args - Arguments to update many Common_apis.
   * @example
   * // Update many Common_apis
   * const common_api = await prisma.common_api.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_apis and only return the `api_id`
   * const common_apiWithApi_idOnly = await prisma.common_api.updateManyAndReturn({
   *   select: { api_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_apiUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_apiUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_api.
   * @param {common_apiUpsertArgs} args - Arguments to update or create a Common_api.
   * @example
   * // Update or create a Common_api
   * const common_api = await prisma.common_api.upsert({
   *   create: {
   *     // ... data to create a Common_api
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_api we want to update
   *   }
   * })
   */
  upsert<T extends common_apiUpsertArgs>(args: Prisma.SelectSubset<T, common_apiUpsertArgs<ExtArgs>>): Prisma.Prisma__common_apiClient<runtime.Types.Result.GetResult<Prisma.$common_apiPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_apis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiCountArgs} args - Arguments to filter Common_apis to count.
   * @example
   * // Count the number of Common_apis
   * const count = await prisma.common_api.count({
   *   where: {
   *     // ... the filter for the Common_apis we want to count
   *   }
   * })
  **/
  count<T extends common_apiCountArgs>(
    args?: Prisma.Subset<T, common_apiCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_apiCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_api.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_apiAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_apiAggregateArgs>(args: Prisma.Subset<T, Common_apiAggregateArgs>): Prisma.PrismaPromise<GetCommon_apiAggregateType<T>>

  /**
   * Group by Common_api.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_apiGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_apiGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_apiGroupByArgs['orderBy'] }
      : { orderBy?: common_apiGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_apiGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_apiGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_api model
 */
readonly fields: common_apiFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_api.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_apiClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_api model
 */
export interface common_apiFieldRefs {
  readonly api_id: Prisma.FieldRef<"common_api", 'Int'>
  readonly api_type: Prisma.FieldRef<"common_api", 'String'>
  readonly api_name: Prisma.FieldRef<"common_api", 'String'>
  readonly api_path: Prisma.FieldRef<"common_api", 'String'>
  readonly api_function: Prisma.FieldRef<"common_api", 'String'>
  readonly auth_flag: Prisma.FieldRef<"common_api", 'String'>
  readonly api_remark: Prisma.FieldRef<"common_api", 'String'>
  readonly state: Prisma.FieldRef<"common_api", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_api", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_api", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_api findUnique
 */
export type common_apiFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter, which common_api to fetch.
   */
  where: Prisma.common_apiWhereUniqueInput
}

/**
 * common_api findUniqueOrThrow
 */
export type common_apiFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter, which common_api to fetch.
   */
  where: Prisma.common_apiWhereUniqueInput
}

/**
 * common_api findFirst
 */
export type common_apiFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter, which common_api to fetch.
   */
  where?: Prisma.common_apiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_apis to fetch.
   */
  orderBy?: Prisma.common_apiOrderByWithRelationInput | Prisma.common_apiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_apis.
   */
  cursor?: Prisma.common_apiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_apis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_apis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_apis.
   */
  distinct?: Prisma.Common_apiScalarFieldEnum | Prisma.Common_apiScalarFieldEnum[]
}

/**
 * common_api findFirstOrThrow
 */
export type common_apiFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter, which common_api to fetch.
   */
  where?: Prisma.common_apiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_apis to fetch.
   */
  orderBy?: Prisma.common_apiOrderByWithRelationInput | Prisma.common_apiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_apis.
   */
  cursor?: Prisma.common_apiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_apis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_apis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_apis.
   */
  distinct?: Prisma.Common_apiScalarFieldEnum | Prisma.Common_apiScalarFieldEnum[]
}

/**
 * common_api findMany
 */
export type common_apiFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter, which common_apis to fetch.
   */
  where?: Prisma.common_apiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_apis to fetch.
   */
  orderBy?: Prisma.common_apiOrderByWithRelationInput | Prisma.common_apiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_apis.
   */
  cursor?: Prisma.common_apiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_apis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_apis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_apis.
   */
  distinct?: Prisma.Common_apiScalarFieldEnum | Prisma.Common_apiScalarFieldEnum[]
}

/**
 * common_api create
 */
export type common_apiCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * The data needed to create a common_api.
   */
  data: Prisma.XOR<Prisma.common_apiCreateInput, Prisma.common_apiUncheckedCreateInput>
}

/**
 * common_api createMany
 */
export type common_apiCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_apis.
   */
  data: Prisma.common_apiCreateManyInput | Prisma.common_apiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_api createManyAndReturn
 */
export type common_apiCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * The data used to create many common_apis.
   */
  data: Prisma.common_apiCreateManyInput | Prisma.common_apiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_api update
 */
export type common_apiUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * The data needed to update a common_api.
   */
  data: Prisma.XOR<Prisma.common_apiUpdateInput, Prisma.common_apiUncheckedUpdateInput>
  /**
   * Choose, which common_api to update.
   */
  where: Prisma.common_apiWhereUniqueInput
}

/**
 * common_api updateMany
 */
export type common_apiUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_apis.
   */
  data: Prisma.XOR<Prisma.common_apiUpdateManyMutationInput, Prisma.common_apiUncheckedUpdateManyInput>
  /**
   * Filter which common_apis to update
   */
  where?: Prisma.common_apiWhereInput
  /**
   * Limit how many common_apis to update.
   */
  limit?: number
}

/**
 * common_api updateManyAndReturn
 */
export type common_apiUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * The data used to update common_apis.
   */
  data: Prisma.XOR<Prisma.common_apiUpdateManyMutationInput, Prisma.common_apiUncheckedUpdateManyInput>
  /**
   * Filter which common_apis to update
   */
  where?: Prisma.common_apiWhereInput
  /**
   * Limit how many common_apis to update.
   */
  limit?: number
}

/**
 * common_api upsert
 */
export type common_apiUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * The filter to search for the common_api to update in case it exists.
   */
  where: Prisma.common_apiWhereUniqueInput
  /**
   * In case the common_api found by the `where` argument doesn't exist, create a new common_api with this data.
   */
  create: Prisma.XOR<Prisma.common_apiCreateInput, Prisma.common_apiUncheckedCreateInput>
  /**
   * In case the common_api was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_apiUpdateInput, Prisma.common_apiUncheckedUpdateInput>
}

/**
 * common_api delete
 */
export type common_apiDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
  /**
   * Filter which common_api to delete.
   */
  where: Prisma.common_apiWhereUniqueInput
}

/**
 * common_api deleteMany
 */
export type common_apiDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_apis to delete
   */
  where?: Prisma.common_apiWhereInput
  /**
   * Limit how many common_apis to delete.
   */
  limit?: number
}

/**
 * common_api without action
 */
export type common_apiDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_api
   */
  select?: Prisma.common_apiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_api
   */
  omit?: Prisma.common_apiOmit<ExtArgs> | null
}
