
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_group_menu` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_group_menu
 * 
 */
export type common_group_menuModel = runtime.Types.Result.DefaultSelection<Prisma.$common_group_menuPayload>

export type AggregateCommon_group_menu = {
  _count: Common_group_menuCountAggregateOutputType | null
  _avg: Common_group_menuAvgAggregateOutputType | null
  _sum: Common_group_menuSumAggregateOutputType | null
  _min: Common_group_menuMinAggregateOutputType | null
  _max: Common_group_menuMaxAggregateOutputType | null
}

export type Common_group_menuAvgAggregateOutputType = {
  group_menu_id: number | null
  group_id: number | null
  menu_id: number | null
}

export type Common_group_menuSumAggregateOutputType = {
  group_menu_id: number | null
  group_id: number | null
  menu_id: number | null
}

export type Common_group_menuMinAggregateOutputType = {
  group_menu_id: number | null
  group_id: number | null
  menu_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_group_menuMaxAggregateOutputType = {
  group_menu_id: number | null
  group_id: number | null
  menu_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_group_menuCountAggregateOutputType = {
  group_menu_id: number
  group_id: number
  menu_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_group_menuAvgAggregateInputType = {
  group_menu_id?: true
  group_id?: true
  menu_id?: true
}

export type Common_group_menuSumAggregateInputType = {
  group_menu_id?: true
  group_id?: true
  menu_id?: true
}

export type Common_group_menuMinAggregateInputType = {
  group_menu_id?: true
  group_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_group_menuMaxAggregateInputType = {
  group_menu_id?: true
  group_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_group_menuCountAggregateInputType = {
  group_menu_id?: true
  group_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_group_menuAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_group_menu to aggregate.
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_group_menus to fetch.
   */
  orderBy?: Prisma.common_group_menuOrderByWithRelationInput | Prisma.common_group_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_group_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_group_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_group_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_group_menus
  **/
  _count?: true | Common_group_menuCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_group_menuAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_group_menuSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_group_menuMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_group_menuMaxAggregateInputType
}

export type GetCommon_group_menuAggregateType<T extends Common_group_menuAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_group_menu]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_group_menu[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_group_menu[P]>
}




export type common_group_menuGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_group_menuWhereInput
  orderBy?: Prisma.common_group_menuOrderByWithAggregationInput | Prisma.common_group_menuOrderByWithAggregationInput[]
  by: Prisma.Common_group_menuScalarFieldEnum[] | Prisma.Common_group_menuScalarFieldEnum
  having?: Prisma.common_group_menuScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_group_menuCountAggregateInputType | true
  _avg?: Common_group_menuAvgAggregateInputType
  _sum?: Common_group_menuSumAggregateInputType
  _min?: Common_group_menuMinAggregateInputType
  _max?: Common_group_menuMaxAggregateInputType
}

export type Common_group_menuGroupByOutputType = {
  group_menu_id: number
  group_id: number
  menu_id: number
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_group_menuCountAggregateOutputType | null
  _avg: Common_group_menuAvgAggregateOutputType | null
  _sum: Common_group_menuSumAggregateOutputType | null
  _min: Common_group_menuMinAggregateOutputType | null
  _max: Common_group_menuMaxAggregateOutputType | null
}

type GetCommon_group_menuGroupByPayload<T extends common_group_menuGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_group_menuGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_group_menuGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_group_menuGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_group_menuGroupByOutputType[P]>
      }
    >
  >



export type common_group_menuWhereInput = {
  AND?: Prisma.common_group_menuWhereInput | Prisma.common_group_menuWhereInput[]
  OR?: Prisma.common_group_menuWhereInput[]
  NOT?: Prisma.common_group_menuWhereInput | Prisma.common_group_menuWhereInput[]
  group_menu_id?: Prisma.IntFilter<"common_group_menu"> | number
  group_id?: Prisma.IntFilter<"common_group_menu"> | number
  menu_id?: Prisma.IntFilter<"common_group_menu"> | number
  state?: Prisma.StringFilter<"common_group_menu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_group_menu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_group_menu"> | Date | string
}

export type common_group_menuOrderByWithRelationInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_group_menuWhereUniqueInput = Prisma.AtLeast<{
  group_menu_id?: number
  AND?: Prisma.common_group_menuWhereInput | Prisma.common_group_menuWhereInput[]
  OR?: Prisma.common_group_menuWhereInput[]
  NOT?: Prisma.common_group_menuWhereInput | Prisma.common_group_menuWhereInput[]
  group_id?: Prisma.IntFilter<"common_group_menu"> | number
  menu_id?: Prisma.IntFilter<"common_group_menu"> | number
  state?: Prisma.StringFilter<"common_group_menu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_group_menu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_group_menu"> | Date | string
}, "group_menu_id">

export type common_group_menuOrderByWithAggregationInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_group_menuCountOrderByAggregateInput
  _avg?: Prisma.common_group_menuAvgOrderByAggregateInput
  _max?: Prisma.common_group_menuMaxOrderByAggregateInput
  _min?: Prisma.common_group_menuMinOrderByAggregateInput
  _sum?: Prisma.common_group_menuSumOrderByAggregateInput
}

export type common_group_menuScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_group_menuScalarWhereWithAggregatesInput | Prisma.common_group_menuScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_group_menuScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_group_menuScalarWhereWithAggregatesInput | Prisma.common_group_menuScalarWhereWithAggregatesInput[]
  group_menu_id?: Prisma.IntWithAggregatesFilter<"common_group_menu"> | number
  group_id?: Prisma.IntWithAggregatesFilter<"common_group_menu"> | number
  menu_id?: Prisma.IntWithAggregatesFilter<"common_group_menu"> | number
  state?: Prisma.StringWithAggregatesFilter<"common_group_menu"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_group_menu"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_group_menu"> | Date | string
}

export type common_group_menuCreateInput = {
  group_id: number
  menu_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_group_menuUncheckedCreateInput = {
  group_menu_id?: number
  group_id: number
  menu_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_group_menuUpdateInput = {
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_group_menuUncheckedUpdateInput = {
  group_menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_group_menuCreateManyInput = {
  group_menu_id?: number
  group_id: number
  menu_id: number
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_group_menuUpdateManyMutationInput = {
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_group_menuUncheckedUpdateManyInput = {
  group_menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_group_menuCountOrderByAggregateInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_group_menuAvgOrderByAggregateInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}

export type common_group_menuMaxOrderByAggregateInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_group_menuMinOrderByAggregateInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_group_menuSumOrderByAggregateInput = {
  group_menu_id?: Prisma.SortOrder
  group_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}



export type common_group_menuSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_menu_id?: boolean
  group_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group_menu"]>

export type common_group_menuSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_menu_id?: boolean
  group_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group_menu"]>

export type common_group_menuSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_menu_id?: boolean
  group_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group_menu"]>

export type common_group_menuSelectScalar = {
  group_menu_id?: boolean
  group_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_group_menuOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"group_menu_id" | "group_id" | "menu_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_group_menu"]>

export type $common_group_menuPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_group_menu"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    group_menu_id: number
    group_id: number
    menu_id: number
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_group_menu"]>
  composites: {}
}

export type common_group_menuGetPayload<S extends boolean | null | undefined | common_group_menuDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload, S>

export type common_group_menuCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_group_menuFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_group_menuCountAggregateInputType | true
  }

export interface common_group_menuDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_group_menu'], meta: { name: 'common_group_menu' } }
  /**
   * Find zero or one Common_group_menu that matches the filter.
   * @param {common_group_menuFindUniqueArgs} args - Arguments to find a Common_group_menu
   * @example
   * // Get one Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_group_menuFindUniqueArgs>(args: Prisma.SelectSubset<T, common_group_menuFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_group_menu that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_group_menuFindUniqueOrThrowArgs} args - Arguments to find a Common_group_menu
   * @example
   * // Get one Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_group_menuFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_group_menuFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_group_menu that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuFindFirstArgs} args - Arguments to find a Common_group_menu
   * @example
   * // Get one Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_group_menuFindFirstArgs>(args?: Prisma.SelectSubset<T, common_group_menuFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_group_menu that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuFindFirstOrThrowArgs} args - Arguments to find a Common_group_menu
   * @example
   * // Get one Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_group_menuFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_group_menuFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_group_menus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_group_menus
   * const common_group_menus = await prisma.common_group_menu.findMany()
   * 
   * // Get first 10 Common_group_menus
   * const common_group_menus = await prisma.common_group_menu.findMany({ take: 10 })
   * 
   * // Only select the `group_menu_id`
   * const common_group_menuWithGroup_menu_idOnly = await prisma.common_group_menu.findMany({ select: { group_menu_id: true } })
   * 
   */
  findMany<T extends common_group_menuFindManyArgs>(args?: Prisma.SelectSubset<T, common_group_menuFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_group_menu.
   * @param {common_group_menuCreateArgs} args - Arguments to create a Common_group_menu.
   * @example
   * // Create one Common_group_menu
   * const Common_group_menu = await prisma.common_group_menu.create({
   *   data: {
   *     // ... data to create a Common_group_menu
   *   }
   * })
   * 
   */
  create<T extends common_group_menuCreateArgs>(args: Prisma.SelectSubset<T, common_group_menuCreateArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_group_menus.
   * @param {common_group_menuCreateManyArgs} args - Arguments to create many Common_group_menus.
   * @example
   * // Create many Common_group_menus
   * const common_group_menu = await prisma.common_group_menu.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_group_menuCreateManyArgs>(args?: Prisma.SelectSubset<T, common_group_menuCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_group_menus and returns the data saved in the database.
   * @param {common_group_menuCreateManyAndReturnArgs} args - Arguments to create many Common_group_menus.
   * @example
   * // Create many Common_group_menus
   * const common_group_menu = await prisma.common_group_menu.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_group_menus and only return the `group_menu_id`
   * const common_group_menuWithGroup_menu_idOnly = await prisma.common_group_menu.createManyAndReturn({
   *   select: { group_menu_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_group_menuCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_group_menuCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_group_menu.
   * @param {common_group_menuDeleteArgs} args - Arguments to delete one Common_group_menu.
   * @example
   * // Delete one Common_group_menu
   * const Common_group_menu = await prisma.common_group_menu.delete({
   *   where: {
   *     // ... filter to delete one Common_group_menu
   *   }
   * })
   * 
   */
  delete<T extends common_group_menuDeleteArgs>(args: Prisma.SelectSubset<T, common_group_menuDeleteArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_group_menu.
   * @param {common_group_menuUpdateArgs} args - Arguments to update one Common_group_menu.
   * @example
   * // Update one Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_group_menuUpdateArgs>(args: Prisma.SelectSubset<T, common_group_menuUpdateArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_group_menus.
   * @param {common_group_menuDeleteManyArgs} args - Arguments to filter Common_group_menus to delete.
   * @example
   * // Delete a few Common_group_menus
   * const { count } = await prisma.common_group_menu.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_group_menuDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_group_menuDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_group_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_group_menus
   * const common_group_menu = await prisma.common_group_menu.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_group_menuUpdateManyArgs>(args: Prisma.SelectSubset<T, common_group_menuUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_group_menus and returns the data updated in the database.
   * @param {common_group_menuUpdateManyAndReturnArgs} args - Arguments to update many Common_group_menus.
   * @example
   * // Update many Common_group_menus
   * const common_group_menu = await prisma.common_group_menu.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_group_menus and only return the `group_menu_id`
   * const common_group_menuWithGroup_menu_idOnly = await prisma.common_group_menu.updateManyAndReturn({
   *   select: { group_menu_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_group_menuUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_group_menuUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_group_menu.
   * @param {common_group_menuUpsertArgs} args - Arguments to update or create a Common_group_menu.
   * @example
   * // Update or create a Common_group_menu
   * const common_group_menu = await prisma.common_group_menu.upsert({
   *   create: {
   *     // ... data to create a Common_group_menu
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_group_menu we want to update
   *   }
   * })
   */
  upsert<T extends common_group_menuUpsertArgs>(args: Prisma.SelectSubset<T, common_group_menuUpsertArgs<ExtArgs>>): Prisma.Prisma__common_group_menuClient<runtime.Types.Result.GetResult<Prisma.$common_group_menuPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_group_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuCountArgs} args - Arguments to filter Common_group_menus to count.
   * @example
   * // Count the number of Common_group_menus
   * const count = await prisma.common_group_menu.count({
   *   where: {
   *     // ... the filter for the Common_group_menus we want to count
   *   }
   * })
  **/
  count<T extends common_group_menuCountArgs>(
    args?: Prisma.Subset<T, common_group_menuCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_group_menuCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_group_menu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_group_menuAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_group_menuAggregateArgs>(args: Prisma.Subset<T, Common_group_menuAggregateArgs>): Prisma.PrismaPromise<GetCommon_group_menuAggregateType<T>>

  /**
   * Group by Common_group_menu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_group_menuGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_group_menuGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_group_menuGroupByArgs['orderBy'] }
      : { orderBy?: common_group_menuGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_group_menuGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_group_menuGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_group_menu model
 */
readonly fields: common_group_menuFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_group_menu.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_group_menuClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_group_menu model
 */
export interface common_group_menuFieldRefs {
  readonly group_menu_id: Prisma.FieldRef<"common_group_menu", 'Int'>
  readonly group_id: Prisma.FieldRef<"common_group_menu", 'Int'>
  readonly menu_id: Prisma.FieldRef<"common_group_menu", 'Int'>
  readonly state: Prisma.FieldRef<"common_group_menu", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_group_menu", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_group_menu", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_group_menu findUnique
 */
export type common_group_menuFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_group_menu to fetch.
   */
  where: Prisma.common_group_menuWhereUniqueInput
}

/**
 * common_group_menu findUniqueOrThrow
 */
export type common_group_menuFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_group_menu to fetch.
   */
  where: Prisma.common_group_menuWhereUniqueInput
}

/**
 * common_group_menu findFirst
 */
export type common_group_menuFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_group_menu to fetch.
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_group_menus to fetch.
   */
  orderBy?: Prisma.common_group_menuOrderByWithRelationInput | Prisma.common_group_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_group_menus.
   */
  cursor?: Prisma.common_group_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_group_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_group_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_group_menus.
   */
  distinct?: Prisma.Common_group_menuScalarFieldEnum | Prisma.Common_group_menuScalarFieldEnum[]
}

/**
 * common_group_menu findFirstOrThrow
 */
export type common_group_menuFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_group_menu to fetch.
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_group_menus to fetch.
   */
  orderBy?: Prisma.common_group_menuOrderByWithRelationInput | Prisma.common_group_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_group_menus.
   */
  cursor?: Prisma.common_group_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_group_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_group_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_group_menus.
   */
  distinct?: Prisma.Common_group_menuScalarFieldEnum | Prisma.Common_group_menuScalarFieldEnum[]
}

/**
 * common_group_menu findMany
 */
export type common_group_menuFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_group_menus to fetch.
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_group_menus to fetch.
   */
  orderBy?: Prisma.common_group_menuOrderByWithRelationInput | Prisma.common_group_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_group_menus.
   */
  cursor?: Prisma.common_group_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_group_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_group_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_group_menus.
   */
  distinct?: Prisma.Common_group_menuScalarFieldEnum | Prisma.Common_group_menuScalarFieldEnum[]
}

/**
 * common_group_menu create
 */
export type common_group_menuCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * The data needed to create a common_group_menu.
   */
  data: Prisma.XOR<Prisma.common_group_menuCreateInput, Prisma.common_group_menuUncheckedCreateInput>
}

/**
 * common_group_menu createMany
 */
export type common_group_menuCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_group_menus.
   */
  data: Prisma.common_group_menuCreateManyInput | Prisma.common_group_menuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_group_menu createManyAndReturn
 */
export type common_group_menuCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * The data used to create many common_group_menus.
   */
  data: Prisma.common_group_menuCreateManyInput | Prisma.common_group_menuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_group_menu update
 */
export type common_group_menuUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * The data needed to update a common_group_menu.
   */
  data: Prisma.XOR<Prisma.common_group_menuUpdateInput, Prisma.common_group_menuUncheckedUpdateInput>
  /**
   * Choose, which common_group_menu to update.
   */
  where: Prisma.common_group_menuWhereUniqueInput
}

/**
 * common_group_menu updateMany
 */
export type common_group_menuUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_group_menus.
   */
  data: Prisma.XOR<Prisma.common_group_menuUpdateManyMutationInput, Prisma.common_group_menuUncheckedUpdateManyInput>
  /**
   * Filter which common_group_menus to update
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * Limit how many common_group_menus to update.
   */
  limit?: number
}

/**
 * common_group_menu updateManyAndReturn
 */
export type common_group_menuUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * The data used to update common_group_menus.
   */
  data: Prisma.XOR<Prisma.common_group_menuUpdateManyMutationInput, Prisma.common_group_menuUncheckedUpdateManyInput>
  /**
   * Filter which common_group_menus to update
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * Limit how many common_group_menus to update.
   */
  limit?: number
}

/**
 * common_group_menu upsert
 */
export type common_group_menuUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * The filter to search for the common_group_menu to update in case it exists.
   */
  where: Prisma.common_group_menuWhereUniqueInput
  /**
   * In case the common_group_menu found by the `where` argument doesn't exist, create a new common_group_menu with this data.
   */
  create: Prisma.XOR<Prisma.common_group_menuCreateInput, Prisma.common_group_menuUncheckedCreateInput>
  /**
   * In case the common_group_menu was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_group_menuUpdateInput, Prisma.common_group_menuUncheckedUpdateInput>
}

/**
 * common_group_menu delete
 */
export type common_group_menuDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
  /**
   * Filter which common_group_menu to delete.
   */
  where: Prisma.common_group_menuWhereUniqueInput
}

/**
 * common_group_menu deleteMany
 */
export type common_group_menuDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_group_menus to delete
   */
  where?: Prisma.common_group_menuWhereInput
  /**
   * Limit how many common_group_menus to delete.
   */
  limit?: number
}

/**
 * common_group_menu without action
 */
export type common_group_menuDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group_menu
   */
  select?: Prisma.common_group_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group_menu
   */
  omit?: Prisma.common_group_menuOmit<ExtArgs> | null
}
