
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_usergroupmenu` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_usergroupmenu
 * 
 */
export type common_usergroupmenuModel = runtime.Types.Result.DefaultSelection<Prisma.$common_usergroupmenuPayload>

export type AggregateCommon_usergroupmenu = {
  _count: Common_usergroupmenuCountAggregateOutputType | null
  _avg: Common_usergroupmenuAvgAggregateOutputType | null
  _sum: Common_usergroupmenuSumAggregateOutputType | null
  _min: Common_usergroupmenuMinAggregateOutputType | null
  _max: Common_usergroupmenuMaxAggregateOutputType | null
}

export type Common_usergroupmenuAvgAggregateOutputType = {
  usergroupmenu_id: number | null
  usergroup_id: number | null
  menu_id: number | null
}

export type Common_usergroupmenuSumAggregateOutputType = {
  usergroupmenu_id: number | null
  usergroup_id: number | null
  menu_id: number | null
}

export type Common_usergroupmenuMinAggregateOutputType = {
  usergroupmenu_id: number | null
  usergroup_id: number | null
  menu_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_usergroupmenuMaxAggregateOutputType = {
  usergroupmenu_id: number | null
  usergroup_id: number | null
  menu_id: number | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_usergroupmenuCountAggregateOutputType = {
  usergroupmenu_id: number
  usergroup_id: number
  menu_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_usergroupmenuAvgAggregateInputType = {
  usergroupmenu_id?: true
  usergroup_id?: true
  menu_id?: true
}

export type Common_usergroupmenuSumAggregateInputType = {
  usergroupmenu_id?: true
  usergroup_id?: true
  menu_id?: true
}

export type Common_usergroupmenuMinAggregateInputType = {
  usergroupmenu_id?: true
  usergroup_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_usergroupmenuMaxAggregateInputType = {
  usergroupmenu_id?: true
  usergroup_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_usergroupmenuCountAggregateInputType = {
  usergroupmenu_id?: true
  usergroup_id?: true
  menu_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_usergroupmenuAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_usergroupmenu to aggregate.
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroupmenus to fetch.
   */
  orderBy?: Prisma.common_usergroupmenuOrderByWithRelationInput | Prisma.common_usergroupmenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_usergroupmenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroupmenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroupmenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_usergroupmenus
  **/
  _count?: true | Common_usergroupmenuCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_usergroupmenuAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_usergroupmenuSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_usergroupmenuMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_usergroupmenuMaxAggregateInputType
}

export type GetCommon_usergroupmenuAggregateType<T extends Common_usergroupmenuAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_usergroupmenu]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_usergroupmenu[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_usergroupmenu[P]>
}




export type common_usergroupmenuGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_usergroupmenuWhereInput
  orderBy?: Prisma.common_usergroupmenuOrderByWithAggregationInput | Prisma.common_usergroupmenuOrderByWithAggregationInput[]
  by: Prisma.Common_usergroupmenuScalarFieldEnum[] | Prisma.Common_usergroupmenuScalarFieldEnum
  having?: Prisma.common_usergroupmenuScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_usergroupmenuCountAggregateInputType | true
  _avg?: Common_usergroupmenuAvgAggregateInputType
  _sum?: Common_usergroupmenuSumAggregateInputType
  _min?: Common_usergroupmenuMinAggregateInputType
  _max?: Common_usergroupmenuMaxAggregateInputType
}

export type Common_usergroupmenuGroupByOutputType = {
  usergroupmenu_id: number
  usergroup_id: number
  menu_id: number
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_usergroupmenuCountAggregateOutputType | null
  _avg: Common_usergroupmenuAvgAggregateOutputType | null
  _sum: Common_usergroupmenuSumAggregateOutputType | null
  _min: Common_usergroupmenuMinAggregateOutputType | null
  _max: Common_usergroupmenuMaxAggregateOutputType | null
}

type GetCommon_usergroupmenuGroupByPayload<T extends common_usergroupmenuGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_usergroupmenuGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_usergroupmenuGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_usergroupmenuGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_usergroupmenuGroupByOutputType[P]>
      }
    >
  >



export type common_usergroupmenuWhereInput = {
  AND?: Prisma.common_usergroupmenuWhereInput | Prisma.common_usergroupmenuWhereInput[]
  OR?: Prisma.common_usergroupmenuWhereInput[]
  NOT?: Prisma.common_usergroupmenuWhereInput | Prisma.common_usergroupmenuWhereInput[]
  usergroupmenu_id?: Prisma.IntFilter<"common_usergroupmenu"> | number
  usergroup_id?: Prisma.IntFilter<"common_usergroupmenu"> | number
  menu_id?: Prisma.IntFilter<"common_usergroupmenu"> | number
  state?: Prisma.StringFilter<"common_usergroupmenu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_usergroupmenu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_usergroupmenu"> | Date | string
}

export type common_usergroupmenuOrderByWithRelationInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupmenuWhereUniqueInput = Prisma.AtLeast<{
  usergroupmenu_id?: number
  AND?: Prisma.common_usergroupmenuWhereInput | Prisma.common_usergroupmenuWhereInput[]
  OR?: Prisma.common_usergroupmenuWhereInput[]
  NOT?: Prisma.common_usergroupmenuWhereInput | Prisma.common_usergroupmenuWhereInput[]
  usergroup_id?: Prisma.IntFilter<"common_usergroupmenu"> | number
  menu_id?: Prisma.IntFilter<"common_usergroupmenu"> | number
  state?: Prisma.StringFilter<"common_usergroupmenu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_usergroupmenu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_usergroupmenu"> | Date | string
}, "usergroupmenu_id">

export type common_usergroupmenuOrderByWithAggregationInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_usergroupmenuCountOrderByAggregateInput
  _avg?: Prisma.common_usergroupmenuAvgOrderByAggregateInput
  _max?: Prisma.common_usergroupmenuMaxOrderByAggregateInput
  _min?: Prisma.common_usergroupmenuMinOrderByAggregateInput
  _sum?: Prisma.common_usergroupmenuSumOrderByAggregateInput
}

export type common_usergroupmenuScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_usergroupmenuScalarWhereWithAggregatesInput | Prisma.common_usergroupmenuScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_usergroupmenuScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_usergroupmenuScalarWhereWithAggregatesInput | Prisma.common_usergroupmenuScalarWhereWithAggregatesInput[]
  usergroupmenu_id?: Prisma.IntWithAggregatesFilter<"common_usergroupmenu"> | number
  usergroup_id?: Prisma.IntWithAggregatesFilter<"common_usergroupmenu"> | number
  menu_id?: Prisma.IntWithAggregatesFilter<"common_usergroupmenu"> | number
  state?: Prisma.StringWithAggregatesFilter<"common_usergroupmenu"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_usergroupmenu"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_usergroupmenu"> | Date | string
}

export type common_usergroupmenuCreateInput = {
  usergroup_id: number
  menu_id: number
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupmenuUncheckedCreateInput = {
  usergroupmenu_id?: number
  usergroup_id: number
  menu_id: number
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupmenuUpdateInput = {
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupmenuUncheckedUpdateInput = {
  usergroupmenu_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupmenuCreateManyInput = {
  usergroupmenu_id?: number
  usergroup_id: number
  menu_id: number
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupmenuUpdateManyMutationInput = {
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupmenuUncheckedUpdateManyInput = {
  usergroupmenu_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupmenuCountOrderByAggregateInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupmenuAvgOrderByAggregateInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}

export type common_usergroupmenuMaxOrderByAggregateInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupmenuMinOrderByAggregateInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupmenuSumOrderByAggregateInput = {
  usergroupmenu_id?: Prisma.SortOrder
  usergroup_id?: Prisma.SortOrder
  menu_id?: Prisma.SortOrder
}



export type common_usergroupmenuSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroupmenu_id?: boolean
  usergroup_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroupmenu"]>

export type common_usergroupmenuSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroupmenu_id?: boolean
  usergroup_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroupmenu"]>

export type common_usergroupmenuSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroupmenu_id?: boolean
  usergroup_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroupmenu"]>

export type common_usergroupmenuSelectScalar = {
  usergroupmenu_id?: boolean
  usergroup_id?: boolean
  menu_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_usergroupmenuOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"usergroupmenu_id" | "usergroup_id" | "menu_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_usergroupmenu"]>

export type $common_usergroupmenuPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_usergroupmenu"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    usergroupmenu_id: number
    usergroup_id: number
    menu_id: number
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_usergroupmenu"]>
  composites: {}
}

export type common_usergroupmenuGetPayload<S extends boolean | null | undefined | common_usergroupmenuDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload, S>

export type common_usergroupmenuCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_usergroupmenuFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_usergroupmenuCountAggregateInputType | true
  }

export interface common_usergroupmenuDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_usergroupmenu'], meta: { name: 'common_usergroupmenu' } }
  /**
   * Find zero or one Common_usergroupmenu that matches the filter.
   * @param {common_usergroupmenuFindUniqueArgs} args - Arguments to find a Common_usergroupmenu
   * @example
   * // Get one Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_usergroupmenuFindUniqueArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_usergroupmenu that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_usergroupmenuFindUniqueOrThrowArgs} args - Arguments to find a Common_usergroupmenu
   * @example
   * // Get one Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_usergroupmenuFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_usergroupmenu that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuFindFirstArgs} args - Arguments to find a Common_usergroupmenu
   * @example
   * // Get one Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_usergroupmenuFindFirstArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_usergroupmenu that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuFindFirstOrThrowArgs} args - Arguments to find a Common_usergroupmenu
   * @example
   * // Get one Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_usergroupmenuFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_usergroupmenus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_usergroupmenus
   * const common_usergroupmenus = await prisma.common_usergroupmenu.findMany()
   * 
   * // Get first 10 Common_usergroupmenus
   * const common_usergroupmenus = await prisma.common_usergroupmenu.findMany({ take: 10 })
   * 
   * // Only select the `usergroupmenu_id`
   * const common_usergroupmenuWithUsergroupmenu_idOnly = await prisma.common_usergroupmenu.findMany({ select: { usergroupmenu_id: true } })
   * 
   */
  findMany<T extends common_usergroupmenuFindManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_usergroupmenu.
   * @param {common_usergroupmenuCreateArgs} args - Arguments to create a Common_usergroupmenu.
   * @example
   * // Create one Common_usergroupmenu
   * const Common_usergroupmenu = await prisma.common_usergroupmenu.create({
   *   data: {
   *     // ... data to create a Common_usergroupmenu
   *   }
   * })
   * 
   */
  create<T extends common_usergroupmenuCreateArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuCreateArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_usergroupmenus.
   * @param {common_usergroupmenuCreateManyArgs} args - Arguments to create many Common_usergroupmenus.
   * @example
   * // Create many Common_usergroupmenus
   * const common_usergroupmenu = await prisma.common_usergroupmenu.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_usergroupmenuCreateManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_usergroupmenus and returns the data saved in the database.
   * @param {common_usergroupmenuCreateManyAndReturnArgs} args - Arguments to create many Common_usergroupmenus.
   * @example
   * // Create many Common_usergroupmenus
   * const common_usergroupmenu = await prisma.common_usergroupmenu.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_usergroupmenus and only return the `usergroupmenu_id`
   * const common_usergroupmenuWithUsergroupmenu_idOnly = await prisma.common_usergroupmenu.createManyAndReturn({
   *   select: { usergroupmenu_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_usergroupmenuCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_usergroupmenu.
   * @param {common_usergroupmenuDeleteArgs} args - Arguments to delete one Common_usergroupmenu.
   * @example
   * // Delete one Common_usergroupmenu
   * const Common_usergroupmenu = await prisma.common_usergroupmenu.delete({
   *   where: {
   *     // ... filter to delete one Common_usergroupmenu
   *   }
   * })
   * 
   */
  delete<T extends common_usergroupmenuDeleteArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuDeleteArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_usergroupmenu.
   * @param {common_usergroupmenuUpdateArgs} args - Arguments to update one Common_usergroupmenu.
   * @example
   * // Update one Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_usergroupmenuUpdateArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuUpdateArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_usergroupmenus.
   * @param {common_usergroupmenuDeleteManyArgs} args - Arguments to filter Common_usergroupmenus to delete.
   * @example
   * // Delete a few Common_usergroupmenus
   * const { count } = await prisma.common_usergroupmenu.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_usergroupmenuDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupmenuDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_usergroupmenus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_usergroupmenus
   * const common_usergroupmenu = await prisma.common_usergroupmenu.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_usergroupmenuUpdateManyArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_usergroupmenus and returns the data updated in the database.
   * @param {common_usergroupmenuUpdateManyAndReturnArgs} args - Arguments to update many Common_usergroupmenus.
   * @example
   * // Update many Common_usergroupmenus
   * const common_usergroupmenu = await prisma.common_usergroupmenu.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_usergroupmenus and only return the `usergroupmenu_id`
   * const common_usergroupmenuWithUsergroupmenu_idOnly = await prisma.common_usergroupmenu.updateManyAndReturn({
   *   select: { usergroupmenu_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_usergroupmenuUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_usergroupmenu.
   * @param {common_usergroupmenuUpsertArgs} args - Arguments to update or create a Common_usergroupmenu.
   * @example
   * // Update or create a Common_usergroupmenu
   * const common_usergroupmenu = await prisma.common_usergroupmenu.upsert({
   *   create: {
   *     // ... data to create a Common_usergroupmenu
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_usergroupmenu we want to update
   *   }
   * })
   */
  upsert<T extends common_usergroupmenuUpsertArgs>(args: Prisma.SelectSubset<T, common_usergroupmenuUpsertArgs<ExtArgs>>): Prisma.Prisma__common_usergroupmenuClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupmenuPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_usergroupmenus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuCountArgs} args - Arguments to filter Common_usergroupmenus to count.
   * @example
   * // Count the number of Common_usergroupmenus
   * const count = await prisma.common_usergroupmenu.count({
   *   where: {
   *     // ... the filter for the Common_usergroupmenus we want to count
   *   }
   * })
  **/
  count<T extends common_usergroupmenuCountArgs>(
    args?: Prisma.Subset<T, common_usergroupmenuCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_usergroupmenuCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_usergroupmenu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_usergroupmenuAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_usergroupmenuAggregateArgs>(args: Prisma.Subset<T, Common_usergroupmenuAggregateArgs>): Prisma.PrismaPromise<GetCommon_usergroupmenuAggregateType<T>>

  /**
   * Group by Common_usergroupmenu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupmenuGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_usergroupmenuGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_usergroupmenuGroupByArgs['orderBy'] }
      : { orderBy?: common_usergroupmenuGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_usergroupmenuGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_usergroupmenuGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_usergroupmenu model
 */
readonly fields: common_usergroupmenuFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_usergroupmenu.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_usergroupmenuClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_usergroupmenu model
 */
export interface common_usergroupmenuFieldRefs {
  readonly usergroupmenu_id: Prisma.FieldRef<"common_usergroupmenu", 'Int'>
  readonly usergroup_id: Prisma.FieldRef<"common_usergroupmenu", 'Int'>
  readonly menu_id: Prisma.FieldRef<"common_usergroupmenu", 'Int'>
  readonly state: Prisma.FieldRef<"common_usergroupmenu", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_usergroupmenu", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_usergroupmenu", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_usergroupmenu findUnique
 */
export type common_usergroupmenuFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroupmenu to fetch.
   */
  where: Prisma.common_usergroupmenuWhereUniqueInput
}

/**
 * common_usergroupmenu findUniqueOrThrow
 */
export type common_usergroupmenuFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroupmenu to fetch.
   */
  where: Prisma.common_usergroupmenuWhereUniqueInput
}

/**
 * common_usergroupmenu findFirst
 */
export type common_usergroupmenuFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroupmenu to fetch.
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroupmenus to fetch.
   */
  orderBy?: Prisma.common_usergroupmenuOrderByWithRelationInput | Prisma.common_usergroupmenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_usergroupmenus.
   */
  cursor?: Prisma.common_usergroupmenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroupmenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroupmenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroupmenus.
   */
  distinct?: Prisma.Common_usergroupmenuScalarFieldEnum | Prisma.Common_usergroupmenuScalarFieldEnum[]
}

/**
 * common_usergroupmenu findFirstOrThrow
 */
export type common_usergroupmenuFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroupmenu to fetch.
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroupmenus to fetch.
   */
  orderBy?: Prisma.common_usergroupmenuOrderByWithRelationInput | Prisma.common_usergroupmenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_usergroupmenus.
   */
  cursor?: Prisma.common_usergroupmenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroupmenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroupmenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroupmenus.
   */
  distinct?: Prisma.Common_usergroupmenuScalarFieldEnum | Prisma.Common_usergroupmenuScalarFieldEnum[]
}

/**
 * common_usergroupmenu findMany
 */
export type common_usergroupmenuFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroupmenus to fetch.
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroupmenus to fetch.
   */
  orderBy?: Prisma.common_usergroupmenuOrderByWithRelationInput | Prisma.common_usergroupmenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_usergroupmenus.
   */
  cursor?: Prisma.common_usergroupmenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroupmenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroupmenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroupmenus.
   */
  distinct?: Prisma.Common_usergroupmenuScalarFieldEnum | Prisma.Common_usergroupmenuScalarFieldEnum[]
}

/**
 * common_usergroupmenu create
 */
export type common_usergroupmenuCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * The data needed to create a common_usergroupmenu.
   */
  data: Prisma.XOR<Prisma.common_usergroupmenuCreateInput, Prisma.common_usergroupmenuUncheckedCreateInput>
}

/**
 * common_usergroupmenu createMany
 */
export type common_usergroupmenuCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_usergroupmenus.
   */
  data: Prisma.common_usergroupmenuCreateManyInput | Prisma.common_usergroupmenuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_usergroupmenu createManyAndReturn
 */
export type common_usergroupmenuCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * The data used to create many common_usergroupmenus.
   */
  data: Prisma.common_usergroupmenuCreateManyInput | Prisma.common_usergroupmenuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_usergroupmenu update
 */
export type common_usergroupmenuUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * The data needed to update a common_usergroupmenu.
   */
  data: Prisma.XOR<Prisma.common_usergroupmenuUpdateInput, Prisma.common_usergroupmenuUncheckedUpdateInput>
  /**
   * Choose, which common_usergroupmenu to update.
   */
  where: Prisma.common_usergroupmenuWhereUniqueInput
}

/**
 * common_usergroupmenu updateMany
 */
export type common_usergroupmenuUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_usergroupmenus.
   */
  data: Prisma.XOR<Prisma.common_usergroupmenuUpdateManyMutationInput, Prisma.common_usergroupmenuUncheckedUpdateManyInput>
  /**
   * Filter which common_usergroupmenus to update
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * Limit how many common_usergroupmenus to update.
   */
  limit?: number
}

/**
 * common_usergroupmenu updateManyAndReturn
 */
export type common_usergroupmenuUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * The data used to update common_usergroupmenus.
   */
  data: Prisma.XOR<Prisma.common_usergroupmenuUpdateManyMutationInput, Prisma.common_usergroupmenuUncheckedUpdateManyInput>
  /**
   * Filter which common_usergroupmenus to update
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * Limit how many common_usergroupmenus to update.
   */
  limit?: number
}

/**
 * common_usergroupmenu upsert
 */
export type common_usergroupmenuUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * The filter to search for the common_usergroupmenu to update in case it exists.
   */
  where: Prisma.common_usergroupmenuWhereUniqueInput
  /**
   * In case the common_usergroupmenu found by the `where` argument doesn't exist, create a new common_usergroupmenu with this data.
   */
  create: Prisma.XOR<Prisma.common_usergroupmenuCreateInput, Prisma.common_usergroupmenuUncheckedCreateInput>
  /**
   * In case the common_usergroupmenu was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_usergroupmenuUpdateInput, Prisma.common_usergroupmenuUncheckedUpdateInput>
}

/**
 * common_usergroupmenu delete
 */
export type common_usergroupmenuDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
  /**
   * Filter which common_usergroupmenu to delete.
   */
  where: Prisma.common_usergroupmenuWhereUniqueInput
}

/**
 * common_usergroupmenu deleteMany
 */
export type common_usergroupmenuDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_usergroupmenus to delete
   */
  where?: Prisma.common_usergroupmenuWhereInput
  /**
   * Limit how many common_usergroupmenus to delete.
   */
  limit?: number
}

/**
 * common_usergroupmenu without action
 */
export type common_usergroupmenuDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroupmenu
   */
  select?: Prisma.common_usergroupmenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroupmenu
   */
  omit?: Prisma.common_usergroupmenuOmit<ExtArgs> | null
}
