
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_usergroup` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_usergroup
 * 
 */
export type common_usergroupModel = runtime.Types.Result.DefaultSelection<Prisma.$common_usergroupPayload>

export type AggregateCommon_usergroup = {
  _count: Common_usergroupCountAggregateOutputType | null
  _avg: Common_usergroupAvgAggregateOutputType | null
  _sum: Common_usergroupSumAggregateOutputType | null
  _min: Common_usergroupMinAggregateOutputType | null
  _max: Common_usergroupMaxAggregateOutputType | null
}

export type Common_usergroupAvgAggregateOutputType = {
  usergroup_id: number | null
  organization_id: number | null
}

export type Common_usergroupSumAggregateOutputType = {
  usergroup_id: number | null
  organization_id: number | null
}

export type Common_usergroupMinAggregateOutputType = {
  usergroup_id: number | null
  organization_id: number | null
  usergroup_type: string | null
  usergroup_code: string | null
  usergroup_name: string | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_usergroupMaxAggregateOutputType = {
  usergroup_id: number | null
  organization_id: number | null
  usergroup_type: string | null
  usergroup_code: string | null
  usergroup_name: string | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_usergroupCountAggregateOutputType = {
  usergroup_id: number
  organization_id: number
  usergroup_type: number
  usergroup_code: number
  usergroup_name: number
  node_type: number
  parent_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_usergroupAvgAggregateInputType = {
  usergroup_id?: true
  organization_id?: true
}

export type Common_usergroupSumAggregateInputType = {
  usergroup_id?: true
  organization_id?: true
}

export type Common_usergroupMinAggregateInputType = {
  usergroup_id?: true
  organization_id?: true
  usergroup_type?: true
  usergroup_code?: true
  usergroup_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_usergroupMaxAggregateInputType = {
  usergroup_id?: true
  organization_id?: true
  usergroup_type?: true
  usergroup_code?: true
  usergroup_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_usergroupCountAggregateInputType = {
  usergroup_id?: true
  organization_id?: true
  usergroup_type?: true
  usergroup_code?: true
  usergroup_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_usergroupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_usergroup to aggregate.
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroups to fetch.
   */
  orderBy?: Prisma.common_usergroupOrderByWithRelationInput | Prisma.common_usergroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_usergroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_usergroups
  **/
  _count?: true | Common_usergroupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_usergroupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_usergroupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_usergroupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_usergroupMaxAggregateInputType
}

export type GetCommon_usergroupAggregateType<T extends Common_usergroupAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_usergroup]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_usergroup[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_usergroup[P]>
}




export type common_usergroupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_usergroupWhereInput
  orderBy?: Prisma.common_usergroupOrderByWithAggregationInput | Prisma.common_usergroupOrderByWithAggregationInput[]
  by: Prisma.Common_usergroupScalarFieldEnum[] | Prisma.Common_usergroupScalarFieldEnum
  having?: Prisma.common_usergroupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_usergroupCountAggregateInputType | true
  _avg?: Common_usergroupAvgAggregateInputType
  _sum?: Common_usergroupSumAggregateInputType
  _min?: Common_usergroupMinAggregateInputType
  _max?: Common_usergroupMaxAggregateInputType
}

export type Common_usergroupGroupByOutputType = {
  usergroup_id: number
  organization_id: number
  usergroup_type: string
  usergroup_code: string
  usergroup_name: string
  node_type: string
  parent_id: string
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_usergroupCountAggregateOutputType | null
  _avg: Common_usergroupAvgAggregateOutputType | null
  _sum: Common_usergroupSumAggregateOutputType | null
  _min: Common_usergroupMinAggregateOutputType | null
  _max: Common_usergroupMaxAggregateOutputType | null
}

type GetCommon_usergroupGroupByPayload<T extends common_usergroupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_usergroupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_usergroupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_usergroupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_usergroupGroupByOutputType[P]>
      }
    >
  >



export type common_usergroupWhereInput = {
  AND?: Prisma.common_usergroupWhereInput | Prisma.common_usergroupWhereInput[]
  OR?: Prisma.common_usergroupWhereInput[]
  NOT?: Prisma.common_usergroupWhereInput | Prisma.common_usergroupWhereInput[]
  usergroup_id?: Prisma.IntFilter<"common_usergroup"> | number
  organization_id?: Prisma.IntFilter<"common_usergroup"> | number
  usergroup_type?: Prisma.StringFilter<"common_usergroup"> | string
  usergroup_code?: Prisma.StringFilter<"common_usergroup"> | string
  usergroup_name?: Prisma.StringFilter<"common_usergroup"> | string
  node_type?: Prisma.StringFilter<"common_usergroup"> | string
  parent_id?: Prisma.StringFilter<"common_usergroup"> | string
  state?: Prisma.StringFilter<"common_usergroup"> | string
  updated_at?: Prisma.DateTimeFilter<"common_usergroup"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_usergroup"> | Date | string
}

export type common_usergroupOrderByWithRelationInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  usergroup_type?: Prisma.SortOrder
  usergroup_code?: Prisma.SortOrder
  usergroup_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupWhereUniqueInput = Prisma.AtLeast<{
  usergroup_id?: number
  AND?: Prisma.common_usergroupWhereInput | Prisma.common_usergroupWhereInput[]
  OR?: Prisma.common_usergroupWhereInput[]
  NOT?: Prisma.common_usergroupWhereInput | Prisma.common_usergroupWhereInput[]
  organization_id?: Prisma.IntFilter<"common_usergroup"> | number
  usergroup_type?: Prisma.StringFilter<"common_usergroup"> | string
  usergroup_code?: Prisma.StringFilter<"common_usergroup"> | string
  usergroup_name?: Prisma.StringFilter<"common_usergroup"> | string
  node_type?: Prisma.StringFilter<"common_usergroup"> | string
  parent_id?: Prisma.StringFilter<"common_usergroup"> | string
  state?: Prisma.StringFilter<"common_usergroup"> | string
  updated_at?: Prisma.DateTimeFilter<"common_usergroup"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_usergroup"> | Date | string
}, "usergroup_id">

export type common_usergroupOrderByWithAggregationInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  usergroup_type?: Prisma.SortOrder
  usergroup_code?: Prisma.SortOrder
  usergroup_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_usergroupCountOrderByAggregateInput
  _avg?: Prisma.common_usergroupAvgOrderByAggregateInput
  _max?: Prisma.common_usergroupMaxOrderByAggregateInput
  _min?: Prisma.common_usergroupMinOrderByAggregateInput
  _sum?: Prisma.common_usergroupSumOrderByAggregateInput
}

export type common_usergroupScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_usergroupScalarWhereWithAggregatesInput | Prisma.common_usergroupScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_usergroupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_usergroupScalarWhereWithAggregatesInput | Prisma.common_usergroupScalarWhereWithAggregatesInput[]
  usergroup_id?: Prisma.IntWithAggregatesFilter<"common_usergroup"> | number
  organization_id?: Prisma.IntWithAggregatesFilter<"common_usergroup"> | number
  usergroup_type?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  usergroup_code?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  usergroup_name?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  node_type?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  parent_id?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  state?: Prisma.StringWithAggregatesFilter<"common_usergroup"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_usergroup"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_usergroup"> | Date | string
}

export type common_usergroupCreateInput = {
  organization_id: number
  usergroup_type?: string
  usergroup_code?: string
  usergroup_name?: string
  node_type?: string
  parent_id?: string
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupUncheckedCreateInput = {
  usergroup_id?: number
  organization_id: number
  usergroup_type?: string
  usergroup_code?: string
  usergroup_name?: string
  node_type?: string
  parent_id?: string
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupUpdateInput = {
  organization_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_type?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_code?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupUncheckedUpdateInput = {
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_type?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_code?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupCreateManyInput = {
  usergroup_id?: number
  organization_id: number
  usergroup_type?: string
  usergroup_code?: string
  usergroup_name?: string
  node_type?: string
  parent_id?: string
  state: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_usergroupUpdateManyMutationInput = {
  organization_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_type?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_code?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupUncheckedUpdateManyInput = {
  usergroup_id?: Prisma.IntFieldUpdateOperationsInput | number
  organization_id?: Prisma.IntFieldUpdateOperationsInput | number
  usergroup_type?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_code?: Prisma.StringFieldUpdateOperationsInput | string
  usergroup_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_usergroupCountOrderByAggregateInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  usergroup_type?: Prisma.SortOrder
  usergroup_code?: Prisma.SortOrder
  usergroup_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupAvgOrderByAggregateInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
}

export type common_usergroupMaxOrderByAggregateInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  usergroup_type?: Prisma.SortOrder
  usergroup_code?: Prisma.SortOrder
  usergroup_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupMinOrderByAggregateInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
  usergroup_type?: Prisma.SortOrder
  usergroup_code?: Prisma.SortOrder
  usergroup_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_usergroupSumOrderByAggregateInput = {
  usergroup_id?: Prisma.SortOrder
  organization_id?: Prisma.SortOrder
}



export type common_usergroupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroup_id?: boolean
  organization_id?: boolean
  usergroup_type?: boolean
  usergroup_code?: boolean
  usergroup_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroup"]>

export type common_usergroupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroup_id?: boolean
  organization_id?: boolean
  usergroup_type?: boolean
  usergroup_code?: boolean
  usergroup_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroup"]>

export type common_usergroupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  usergroup_id?: boolean
  organization_id?: boolean
  usergroup_type?: boolean
  usergroup_code?: boolean
  usergroup_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_usergroup"]>

export type common_usergroupSelectScalar = {
  usergroup_id?: boolean
  organization_id?: boolean
  usergroup_type?: boolean
  usergroup_code?: boolean
  usergroup_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_usergroupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"usergroup_id" | "organization_id" | "usergroup_type" | "usergroup_code" | "usergroup_name" | "node_type" | "parent_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_usergroup"]>

export type $common_usergroupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_usergroup"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    usergroup_id: number
    organization_id: number
    usergroup_type: string
    usergroup_code: string
    usergroup_name: string
    node_type: string
    parent_id: string
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_usergroup"]>
  composites: {}
}

export type common_usergroupGetPayload<S extends boolean | null | undefined | common_usergroupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload, S>

export type common_usergroupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_usergroupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_usergroupCountAggregateInputType | true
  }

export interface common_usergroupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_usergroup'], meta: { name: 'common_usergroup' } }
  /**
   * Find zero or one Common_usergroup that matches the filter.
   * @param {common_usergroupFindUniqueArgs} args - Arguments to find a Common_usergroup
   * @example
   * // Get one Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_usergroupFindUniqueArgs>(args: Prisma.SelectSubset<T, common_usergroupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_usergroup that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_usergroupFindUniqueOrThrowArgs} args - Arguments to find a Common_usergroup
   * @example
   * // Get one Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_usergroupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_usergroupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_usergroup that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupFindFirstArgs} args - Arguments to find a Common_usergroup
   * @example
   * // Get one Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_usergroupFindFirstArgs>(args?: Prisma.SelectSubset<T, common_usergroupFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_usergroup that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupFindFirstOrThrowArgs} args - Arguments to find a Common_usergroup
   * @example
   * // Get one Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_usergroupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_usergroupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_usergroups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_usergroups
   * const common_usergroups = await prisma.common_usergroup.findMany()
   * 
   * // Get first 10 Common_usergroups
   * const common_usergroups = await prisma.common_usergroup.findMany({ take: 10 })
   * 
   * // Only select the `usergroup_id`
   * const common_usergroupWithUsergroup_idOnly = await prisma.common_usergroup.findMany({ select: { usergroup_id: true } })
   * 
   */
  findMany<T extends common_usergroupFindManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_usergroup.
   * @param {common_usergroupCreateArgs} args - Arguments to create a Common_usergroup.
   * @example
   * // Create one Common_usergroup
   * const Common_usergroup = await prisma.common_usergroup.create({
   *   data: {
   *     // ... data to create a Common_usergroup
   *   }
   * })
   * 
   */
  create<T extends common_usergroupCreateArgs>(args: Prisma.SelectSubset<T, common_usergroupCreateArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_usergroups.
   * @param {common_usergroupCreateManyArgs} args - Arguments to create many Common_usergroups.
   * @example
   * // Create many Common_usergroups
   * const common_usergroup = await prisma.common_usergroup.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_usergroupCreateManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_usergroups and returns the data saved in the database.
   * @param {common_usergroupCreateManyAndReturnArgs} args - Arguments to create many Common_usergroups.
   * @example
   * // Create many Common_usergroups
   * const common_usergroup = await prisma.common_usergroup.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_usergroups and only return the `usergroup_id`
   * const common_usergroupWithUsergroup_idOnly = await prisma.common_usergroup.createManyAndReturn({
   *   select: { usergroup_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_usergroupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_usergroupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_usergroup.
   * @param {common_usergroupDeleteArgs} args - Arguments to delete one Common_usergroup.
   * @example
   * // Delete one Common_usergroup
   * const Common_usergroup = await prisma.common_usergroup.delete({
   *   where: {
   *     // ... filter to delete one Common_usergroup
   *   }
   * })
   * 
   */
  delete<T extends common_usergroupDeleteArgs>(args: Prisma.SelectSubset<T, common_usergroupDeleteArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_usergroup.
   * @param {common_usergroupUpdateArgs} args - Arguments to update one Common_usergroup.
   * @example
   * // Update one Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_usergroupUpdateArgs>(args: Prisma.SelectSubset<T, common_usergroupUpdateArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_usergroups.
   * @param {common_usergroupDeleteManyArgs} args - Arguments to filter Common_usergroups to delete.
   * @example
   * // Delete a few Common_usergroups
   * const { count } = await prisma.common_usergroup.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_usergroupDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_usergroupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_usergroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_usergroups
   * const common_usergroup = await prisma.common_usergroup.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_usergroupUpdateManyArgs>(args: Prisma.SelectSubset<T, common_usergroupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_usergroups and returns the data updated in the database.
   * @param {common_usergroupUpdateManyAndReturnArgs} args - Arguments to update many Common_usergroups.
   * @example
   * // Update many Common_usergroups
   * const common_usergroup = await prisma.common_usergroup.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_usergroups and only return the `usergroup_id`
   * const common_usergroupWithUsergroup_idOnly = await prisma.common_usergroup.updateManyAndReturn({
   *   select: { usergroup_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_usergroupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_usergroupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_usergroup.
   * @param {common_usergroupUpsertArgs} args - Arguments to update or create a Common_usergroup.
   * @example
   * // Update or create a Common_usergroup
   * const common_usergroup = await prisma.common_usergroup.upsert({
   *   create: {
   *     // ... data to create a Common_usergroup
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_usergroup we want to update
   *   }
   * })
   */
  upsert<T extends common_usergroupUpsertArgs>(args: Prisma.SelectSubset<T, common_usergroupUpsertArgs<ExtArgs>>): Prisma.Prisma__common_usergroupClient<runtime.Types.Result.GetResult<Prisma.$common_usergroupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_usergroups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupCountArgs} args - Arguments to filter Common_usergroups to count.
   * @example
   * // Count the number of Common_usergroups
   * const count = await prisma.common_usergroup.count({
   *   where: {
   *     // ... the filter for the Common_usergroups we want to count
   *   }
   * })
  **/
  count<T extends common_usergroupCountArgs>(
    args?: Prisma.Subset<T, common_usergroupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_usergroupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_usergroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_usergroupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_usergroupAggregateArgs>(args: Prisma.Subset<T, Common_usergroupAggregateArgs>): Prisma.PrismaPromise<GetCommon_usergroupAggregateType<T>>

  /**
   * Group by Common_usergroup.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_usergroupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_usergroupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_usergroupGroupByArgs['orderBy'] }
      : { orderBy?: common_usergroupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_usergroupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_usergroupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_usergroup model
 */
readonly fields: common_usergroupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_usergroup.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_usergroupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_usergroup model
 */
export interface common_usergroupFieldRefs {
  readonly usergroup_id: Prisma.FieldRef<"common_usergroup", 'Int'>
  readonly organization_id: Prisma.FieldRef<"common_usergroup", 'Int'>
  readonly usergroup_type: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly usergroup_code: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly usergroup_name: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly node_type: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly parent_id: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly state: Prisma.FieldRef<"common_usergroup", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_usergroup", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_usergroup", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_usergroup findUnique
 */
export type common_usergroupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroup to fetch.
   */
  where: Prisma.common_usergroupWhereUniqueInput
}

/**
 * common_usergroup findUniqueOrThrow
 */
export type common_usergroupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroup to fetch.
   */
  where: Prisma.common_usergroupWhereUniqueInput
}

/**
 * common_usergroup findFirst
 */
export type common_usergroupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroup to fetch.
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroups to fetch.
   */
  orderBy?: Prisma.common_usergroupOrderByWithRelationInput | Prisma.common_usergroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_usergroups.
   */
  cursor?: Prisma.common_usergroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroups.
   */
  distinct?: Prisma.Common_usergroupScalarFieldEnum | Prisma.Common_usergroupScalarFieldEnum[]
}

/**
 * common_usergroup findFirstOrThrow
 */
export type common_usergroupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroup to fetch.
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroups to fetch.
   */
  orderBy?: Prisma.common_usergroupOrderByWithRelationInput | Prisma.common_usergroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_usergroups.
   */
  cursor?: Prisma.common_usergroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroups.
   */
  distinct?: Prisma.Common_usergroupScalarFieldEnum | Prisma.Common_usergroupScalarFieldEnum[]
}

/**
 * common_usergroup findMany
 */
export type common_usergroupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter, which common_usergroups to fetch.
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_usergroups to fetch.
   */
  orderBy?: Prisma.common_usergroupOrderByWithRelationInput | Prisma.common_usergroupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_usergroups.
   */
  cursor?: Prisma.common_usergroupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_usergroups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_usergroups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_usergroups.
   */
  distinct?: Prisma.Common_usergroupScalarFieldEnum | Prisma.Common_usergroupScalarFieldEnum[]
}

/**
 * common_usergroup create
 */
export type common_usergroupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * The data needed to create a common_usergroup.
   */
  data: Prisma.XOR<Prisma.common_usergroupCreateInput, Prisma.common_usergroupUncheckedCreateInput>
}

/**
 * common_usergroup createMany
 */
export type common_usergroupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_usergroups.
   */
  data: Prisma.common_usergroupCreateManyInput | Prisma.common_usergroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_usergroup createManyAndReturn
 */
export type common_usergroupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * The data used to create many common_usergroups.
   */
  data: Prisma.common_usergroupCreateManyInput | Prisma.common_usergroupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_usergroup update
 */
export type common_usergroupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * The data needed to update a common_usergroup.
   */
  data: Prisma.XOR<Prisma.common_usergroupUpdateInput, Prisma.common_usergroupUncheckedUpdateInput>
  /**
   * Choose, which common_usergroup to update.
   */
  where: Prisma.common_usergroupWhereUniqueInput
}

/**
 * common_usergroup updateMany
 */
export type common_usergroupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_usergroups.
   */
  data: Prisma.XOR<Prisma.common_usergroupUpdateManyMutationInput, Prisma.common_usergroupUncheckedUpdateManyInput>
  /**
   * Filter which common_usergroups to update
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * Limit how many common_usergroups to update.
   */
  limit?: number
}

/**
 * common_usergroup updateManyAndReturn
 */
export type common_usergroupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * The data used to update common_usergroups.
   */
  data: Prisma.XOR<Prisma.common_usergroupUpdateManyMutationInput, Prisma.common_usergroupUncheckedUpdateManyInput>
  /**
   * Filter which common_usergroups to update
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * Limit how many common_usergroups to update.
   */
  limit?: number
}

/**
 * common_usergroup upsert
 */
export type common_usergroupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * The filter to search for the common_usergroup to update in case it exists.
   */
  where: Prisma.common_usergroupWhereUniqueInput
  /**
   * In case the common_usergroup found by the `where` argument doesn't exist, create a new common_usergroup with this data.
   */
  create: Prisma.XOR<Prisma.common_usergroupCreateInput, Prisma.common_usergroupUncheckedCreateInput>
  /**
   * In case the common_usergroup was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_usergroupUpdateInput, Prisma.common_usergroupUncheckedUpdateInput>
}

/**
 * common_usergroup delete
 */
export type common_usergroupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
  /**
   * Filter which common_usergroup to delete.
   */
  where: Prisma.common_usergroupWhereUniqueInput
}

/**
 * common_usergroup deleteMany
 */
export type common_usergroupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_usergroups to delete
   */
  where?: Prisma.common_usergroupWhereInput
  /**
   * Limit how many common_usergroups to delete.
   */
  limit?: number
}

/**
 * common_usergroup without action
 */
export type common_usergroupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_usergroup
   */
  select?: Prisma.common_usergroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_usergroup
   */
  omit?: Prisma.common_usergroupOmit<ExtArgs> | null
}
