
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_group` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_group
 * 
 */
export type common_groupModel = runtime.Types.Result.DefaultSelection<Prisma.$common_groupPayload>

export type AggregateCommon_group = {
  _count: Common_groupCountAggregateOutputType | null
  _avg: Common_groupAvgAggregateOutputType | null
  _sum: Common_groupSumAggregateOutputType | null
  _min: Common_groupMinAggregateOutputType | null
  _max: Common_groupMaxAggregateOutputType | null
}

export type Common_groupAvgAggregateOutputType = {
  group_id: number | null
}

export type Common_groupSumAggregateOutputType = {
  group_id: number | null
}

export type Common_groupMinAggregateOutputType = {
  group_id: number | null
  group_type: string | null
  group_code: string | null
  group_name: string | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_groupMaxAggregateOutputType = {
  group_id: number | null
  group_type: string | null
  group_code: string | null
  group_name: string | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_groupCountAggregateOutputType = {
  group_id: number
  group_type: number
  group_code: number
  group_name: number
  node_type: number
  parent_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_groupAvgAggregateInputType = {
  group_id?: true
}

export type Common_groupSumAggregateInputType = {
  group_id?: true
}

export type Common_groupMinAggregateInputType = {
  group_id?: true
  group_type?: true
  group_code?: true
  group_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_groupMaxAggregateInputType = {
  group_id?: true
  group_type?: true
  group_code?: true
  group_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_groupCountAggregateInputType = {
  group_id?: true
  group_type?: true
  group_code?: true
  group_name?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_groupAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_group to aggregate.
   */
  where?: Prisma.common_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_groups to fetch.
   */
  orderBy?: Prisma.common_groupOrderByWithRelationInput | Prisma.common_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_groups
  **/
  _count?: true | Common_groupCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_groupAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_groupSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_groupMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_groupMaxAggregateInputType
}

export type GetCommon_groupAggregateType<T extends Common_groupAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_group]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_group[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_group[P]>
}




export type common_groupGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_groupWhereInput
  orderBy?: Prisma.common_groupOrderByWithAggregationInput | Prisma.common_groupOrderByWithAggregationInput[]
  by: Prisma.Common_groupScalarFieldEnum[] | Prisma.Common_groupScalarFieldEnum
  having?: Prisma.common_groupScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_groupCountAggregateInputType | true
  _avg?: Common_groupAvgAggregateInputType
  _sum?: Common_groupSumAggregateInputType
  _min?: Common_groupMinAggregateInputType
  _max?: Common_groupMaxAggregateInputType
}

export type Common_groupGroupByOutputType = {
  group_id: number
  group_type: string
  group_code: string
  group_name: string
  node_type: string
  parent_id: string
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_groupCountAggregateOutputType | null
  _avg: Common_groupAvgAggregateOutputType | null
  _sum: Common_groupSumAggregateOutputType | null
  _min: Common_groupMinAggregateOutputType | null
  _max: Common_groupMaxAggregateOutputType | null
}

type GetCommon_groupGroupByPayload<T extends common_groupGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_groupGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_groupGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_groupGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_groupGroupByOutputType[P]>
      }
    >
  >



export type common_groupWhereInput = {
  AND?: Prisma.common_groupWhereInput | Prisma.common_groupWhereInput[]
  OR?: Prisma.common_groupWhereInput[]
  NOT?: Prisma.common_groupWhereInput | Prisma.common_groupWhereInput[]
  group_id?: Prisma.IntFilter<"common_group"> | number
  group_type?: Prisma.StringFilter<"common_group"> | string
  group_code?: Prisma.StringFilter<"common_group"> | string
  group_name?: Prisma.StringFilter<"common_group"> | string
  node_type?: Prisma.StringFilter<"common_group"> | string
  parent_id?: Prisma.StringFilter<"common_group"> | string
  state?: Prisma.StringFilter<"common_group"> | string
  updated_at?: Prisma.DateTimeFilter<"common_group"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_group"> | Date | string
}

export type common_groupOrderByWithRelationInput = {
  group_id?: Prisma.SortOrder
  group_type?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_groupWhereUniqueInput = Prisma.AtLeast<{
  group_id?: number
  AND?: Prisma.common_groupWhereInput | Prisma.common_groupWhereInput[]
  OR?: Prisma.common_groupWhereInput[]
  NOT?: Prisma.common_groupWhereInput | Prisma.common_groupWhereInput[]
  group_type?: Prisma.StringFilter<"common_group"> | string
  group_code?: Prisma.StringFilter<"common_group"> | string
  group_name?: Prisma.StringFilter<"common_group"> | string
  node_type?: Prisma.StringFilter<"common_group"> | string
  parent_id?: Prisma.StringFilter<"common_group"> | string
  state?: Prisma.StringFilter<"common_group"> | string
  updated_at?: Prisma.DateTimeFilter<"common_group"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_group"> | Date | string
}, "group_id">

export type common_groupOrderByWithAggregationInput = {
  group_id?: Prisma.SortOrder
  group_type?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_groupCountOrderByAggregateInput
  _avg?: Prisma.common_groupAvgOrderByAggregateInput
  _max?: Prisma.common_groupMaxOrderByAggregateInput
  _min?: Prisma.common_groupMinOrderByAggregateInput
  _sum?: Prisma.common_groupSumOrderByAggregateInput
}

export type common_groupScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_groupScalarWhereWithAggregatesInput | Prisma.common_groupScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_groupScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_groupScalarWhereWithAggregatesInput | Prisma.common_groupScalarWhereWithAggregatesInput[]
  group_id?: Prisma.IntWithAggregatesFilter<"common_group"> | number
  group_type?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  group_code?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  group_name?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  node_type?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  parent_id?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  state?: Prisma.StringWithAggregatesFilter<"common_group"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_group"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_group"> | Date | string
}

export type common_groupCreateInput = {
  group_type?: string
  group_code?: string
  group_name?: string
  node_type?: string
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_groupUncheckedCreateInput = {
  group_id?: number
  group_type?: string
  group_code?: string
  group_name?: string
  node_type?: string
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_groupUpdateInput = {
  group_type?: Prisma.StringFieldUpdateOperationsInput | string
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_groupUncheckedUpdateInput = {
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  group_type?: Prisma.StringFieldUpdateOperationsInput | string
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_groupCreateManyInput = {
  group_id?: number
  group_type?: string
  group_code?: string
  group_name?: string
  node_type?: string
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_groupUpdateManyMutationInput = {
  group_type?: Prisma.StringFieldUpdateOperationsInput | string
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_groupUncheckedUpdateManyInput = {
  group_id?: Prisma.IntFieldUpdateOperationsInput | number
  group_type?: Prisma.StringFieldUpdateOperationsInput | string
  group_code?: Prisma.StringFieldUpdateOperationsInput | string
  group_name?: Prisma.StringFieldUpdateOperationsInput | string
  node_type?: Prisma.StringFieldUpdateOperationsInput | string
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_groupCountOrderByAggregateInput = {
  group_id?: Prisma.SortOrder
  group_type?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_groupAvgOrderByAggregateInput = {
  group_id?: Prisma.SortOrder
}

export type common_groupMaxOrderByAggregateInput = {
  group_id?: Prisma.SortOrder
  group_type?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_groupMinOrderByAggregateInput = {
  group_id?: Prisma.SortOrder
  group_type?: Prisma.SortOrder
  group_code?: Prisma.SortOrder
  group_name?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_groupSumOrderByAggregateInput = {
  group_id?: Prisma.SortOrder
}



export type common_groupSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_id?: boolean
  group_type?: boolean
  group_code?: boolean
  group_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group"]>

export type common_groupSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_id?: boolean
  group_type?: boolean
  group_code?: boolean
  group_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group"]>

export type common_groupSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  group_id?: boolean
  group_type?: boolean
  group_code?: boolean
  group_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_group"]>

export type common_groupSelectScalar = {
  group_id?: boolean
  group_type?: boolean
  group_code?: boolean
  group_name?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_groupOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"group_id" | "group_type" | "group_code" | "group_name" | "node_type" | "parent_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_group"]>

export type $common_groupPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_group"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    group_id: number
    group_type: string
    group_code: string
    group_name: string
    node_type: string
    parent_id: string
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_group"]>
  composites: {}
}

export type common_groupGetPayload<S extends boolean | null | undefined | common_groupDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_groupPayload, S>

export type common_groupCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_groupFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_groupCountAggregateInputType | true
  }

export interface common_groupDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_group'], meta: { name: 'common_group' } }
  /**
   * Find zero or one Common_group that matches the filter.
   * @param {common_groupFindUniqueArgs} args - Arguments to find a Common_group
   * @example
   * // Get one Common_group
   * const common_group = await prisma.common_group.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_groupFindUniqueArgs>(args: Prisma.SelectSubset<T, common_groupFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_group that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_groupFindUniqueOrThrowArgs} args - Arguments to find a Common_group
   * @example
   * // Get one Common_group
   * const common_group = await prisma.common_group.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_groupFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_groupFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_group that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupFindFirstArgs} args - Arguments to find a Common_group
   * @example
   * // Get one Common_group
   * const common_group = await prisma.common_group.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_groupFindFirstArgs>(args?: Prisma.SelectSubset<T, common_groupFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_group that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupFindFirstOrThrowArgs} args - Arguments to find a Common_group
   * @example
   * // Get one Common_group
   * const common_group = await prisma.common_group.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_groupFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_groupFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_groups that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_groups
   * const common_groups = await prisma.common_group.findMany()
   * 
   * // Get first 10 Common_groups
   * const common_groups = await prisma.common_group.findMany({ take: 10 })
   * 
   * // Only select the `group_id`
   * const common_groupWithGroup_idOnly = await prisma.common_group.findMany({ select: { group_id: true } })
   * 
   */
  findMany<T extends common_groupFindManyArgs>(args?: Prisma.SelectSubset<T, common_groupFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_group.
   * @param {common_groupCreateArgs} args - Arguments to create a Common_group.
   * @example
   * // Create one Common_group
   * const Common_group = await prisma.common_group.create({
   *   data: {
   *     // ... data to create a Common_group
   *   }
   * })
   * 
   */
  create<T extends common_groupCreateArgs>(args: Prisma.SelectSubset<T, common_groupCreateArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_groups.
   * @param {common_groupCreateManyArgs} args - Arguments to create many Common_groups.
   * @example
   * // Create many Common_groups
   * const common_group = await prisma.common_group.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_groupCreateManyArgs>(args?: Prisma.SelectSubset<T, common_groupCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_groups and returns the data saved in the database.
   * @param {common_groupCreateManyAndReturnArgs} args - Arguments to create many Common_groups.
   * @example
   * // Create many Common_groups
   * const common_group = await prisma.common_group.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_groups and only return the `group_id`
   * const common_groupWithGroup_idOnly = await prisma.common_group.createManyAndReturn({
   *   select: { group_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_groupCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_groupCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_group.
   * @param {common_groupDeleteArgs} args - Arguments to delete one Common_group.
   * @example
   * // Delete one Common_group
   * const Common_group = await prisma.common_group.delete({
   *   where: {
   *     // ... filter to delete one Common_group
   *   }
   * })
   * 
   */
  delete<T extends common_groupDeleteArgs>(args: Prisma.SelectSubset<T, common_groupDeleteArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_group.
   * @param {common_groupUpdateArgs} args - Arguments to update one Common_group.
   * @example
   * // Update one Common_group
   * const common_group = await prisma.common_group.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_groupUpdateArgs>(args: Prisma.SelectSubset<T, common_groupUpdateArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_groups.
   * @param {common_groupDeleteManyArgs} args - Arguments to filter Common_groups to delete.
   * @example
   * // Delete a few Common_groups
   * const { count } = await prisma.common_group.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_groupDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_groupDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_groups
   * const common_group = await prisma.common_group.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_groupUpdateManyArgs>(args: Prisma.SelectSubset<T, common_groupUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_groups and returns the data updated in the database.
   * @param {common_groupUpdateManyAndReturnArgs} args - Arguments to update many Common_groups.
   * @example
   * // Update many Common_groups
   * const common_group = await prisma.common_group.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_groups and only return the `group_id`
   * const common_groupWithGroup_idOnly = await prisma.common_group.updateManyAndReturn({
   *   select: { group_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_groupUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_groupUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_group.
   * @param {common_groupUpsertArgs} args - Arguments to update or create a Common_group.
   * @example
   * // Update or create a Common_group
   * const common_group = await prisma.common_group.upsert({
   *   create: {
   *     // ... data to create a Common_group
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_group we want to update
   *   }
   * })
   */
  upsert<T extends common_groupUpsertArgs>(args: Prisma.SelectSubset<T, common_groupUpsertArgs<ExtArgs>>): Prisma.Prisma__common_groupClient<runtime.Types.Result.GetResult<Prisma.$common_groupPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_groups.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupCountArgs} args - Arguments to filter Common_groups to count.
   * @example
   * // Count the number of Common_groups
   * const count = await prisma.common_group.count({
   *   where: {
   *     // ... the filter for the Common_groups we want to count
   *   }
   * })
  **/
  count<T extends common_groupCountArgs>(
    args?: Prisma.Subset<T, common_groupCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_groupCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_group.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_groupAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_groupAggregateArgs>(args: Prisma.Subset<T, Common_groupAggregateArgs>): Prisma.PrismaPromise<GetCommon_groupAggregateType<T>>

  /**
   * Group by Common_group.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_groupGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_groupGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_groupGroupByArgs['orderBy'] }
      : { orderBy?: common_groupGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_groupGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_groupGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_group model
 */
readonly fields: common_groupFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_group.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_groupClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_group model
 */
export interface common_groupFieldRefs {
  readonly group_id: Prisma.FieldRef<"common_group", 'Int'>
  readonly group_type: Prisma.FieldRef<"common_group", 'String'>
  readonly group_code: Prisma.FieldRef<"common_group", 'String'>
  readonly group_name: Prisma.FieldRef<"common_group", 'String'>
  readonly node_type: Prisma.FieldRef<"common_group", 'String'>
  readonly parent_id: Prisma.FieldRef<"common_group", 'String'>
  readonly state: Prisma.FieldRef<"common_group", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_group", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_group", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_group findUnique
 */
export type common_groupFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_group to fetch.
   */
  where: Prisma.common_groupWhereUniqueInput
}

/**
 * common_group findUniqueOrThrow
 */
export type common_groupFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_group to fetch.
   */
  where: Prisma.common_groupWhereUniqueInput
}

/**
 * common_group findFirst
 */
export type common_groupFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_group to fetch.
   */
  where?: Prisma.common_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_groups to fetch.
   */
  orderBy?: Prisma.common_groupOrderByWithRelationInput | Prisma.common_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_groups.
   */
  cursor?: Prisma.common_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_groups.
   */
  distinct?: Prisma.Common_groupScalarFieldEnum | Prisma.Common_groupScalarFieldEnum[]
}

/**
 * common_group findFirstOrThrow
 */
export type common_groupFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_group to fetch.
   */
  where?: Prisma.common_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_groups to fetch.
   */
  orderBy?: Prisma.common_groupOrderByWithRelationInput | Prisma.common_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_groups.
   */
  cursor?: Prisma.common_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_groups.
   */
  distinct?: Prisma.Common_groupScalarFieldEnum | Prisma.Common_groupScalarFieldEnum[]
}

/**
 * common_group findMany
 */
export type common_groupFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter, which common_groups to fetch.
   */
  where?: Prisma.common_groupWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_groups to fetch.
   */
  orderBy?: Prisma.common_groupOrderByWithRelationInput | Prisma.common_groupOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_groups.
   */
  cursor?: Prisma.common_groupWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_groups from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_groups.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_groups.
   */
  distinct?: Prisma.Common_groupScalarFieldEnum | Prisma.Common_groupScalarFieldEnum[]
}

/**
 * common_group create
 */
export type common_groupCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * The data needed to create a common_group.
   */
  data: Prisma.XOR<Prisma.common_groupCreateInput, Prisma.common_groupUncheckedCreateInput>
}

/**
 * common_group createMany
 */
export type common_groupCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_groups.
   */
  data: Prisma.common_groupCreateManyInput | Prisma.common_groupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_group createManyAndReturn
 */
export type common_groupCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * The data used to create many common_groups.
   */
  data: Prisma.common_groupCreateManyInput | Prisma.common_groupCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_group update
 */
export type common_groupUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * The data needed to update a common_group.
   */
  data: Prisma.XOR<Prisma.common_groupUpdateInput, Prisma.common_groupUncheckedUpdateInput>
  /**
   * Choose, which common_group to update.
   */
  where: Prisma.common_groupWhereUniqueInput
}

/**
 * common_group updateMany
 */
export type common_groupUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_groups.
   */
  data: Prisma.XOR<Prisma.common_groupUpdateManyMutationInput, Prisma.common_groupUncheckedUpdateManyInput>
  /**
   * Filter which common_groups to update
   */
  where?: Prisma.common_groupWhereInput
  /**
   * Limit how many common_groups to update.
   */
  limit?: number
}

/**
 * common_group updateManyAndReturn
 */
export type common_groupUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * The data used to update common_groups.
   */
  data: Prisma.XOR<Prisma.common_groupUpdateManyMutationInput, Prisma.common_groupUncheckedUpdateManyInput>
  /**
   * Filter which common_groups to update
   */
  where?: Prisma.common_groupWhereInput
  /**
   * Limit how many common_groups to update.
   */
  limit?: number
}

/**
 * common_group upsert
 */
export type common_groupUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * The filter to search for the common_group to update in case it exists.
   */
  where: Prisma.common_groupWhereUniqueInput
  /**
   * In case the common_group found by the `where` argument doesn't exist, create a new common_group with this data.
   */
  create: Prisma.XOR<Prisma.common_groupCreateInput, Prisma.common_groupUncheckedCreateInput>
  /**
   * In case the common_group was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_groupUpdateInput, Prisma.common_groupUncheckedUpdateInput>
}

/**
 * common_group delete
 */
export type common_groupDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
  /**
   * Filter which common_group to delete.
   */
  where: Prisma.common_groupWhereUniqueInput
}

/**
 * common_group deleteMany
 */
export type common_groupDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_groups to delete
   */
  where?: Prisma.common_groupWhereInput
  /**
   * Limit how many common_groups to delete.
   */
  limit?: number
}

/**
 * common_group without action
 */
export type common_groupDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_group
   */
  select?: Prisma.common_groupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_group
   */
  omit?: Prisma.common_groupOmit<ExtArgs> | null
}
