
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `common_system_menu` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model common_system_menu
 * 
 */
export type common_system_menuModel = runtime.Types.Result.DefaultSelection<Prisma.$common_system_menuPayload>

export type AggregateCommon_system_menu = {
  _count: Common_system_menuCountAggregateOutputType | null
  _avg: Common_system_menuAvgAggregateOutputType | null
  _sum: Common_system_menuSumAggregateOutputType | null
  _min: Common_system_menuMinAggregateOutputType | null
  _max: Common_system_menuMaxAggregateOutputType | null
}

export type Common_system_menuAvgAggregateOutputType = {
  menu_id: number | null
  menu_index: number | null
  api_id: number | null
}

export type Common_system_menuSumAggregateOutputType = {
  menu_id: number | null
  menu_index: number | null
  api_id: number | null
}

export type Common_system_menuMinAggregateOutputType = {
  menu_id: number | null
  menu_name: string | null
  menu_icon: string | null
  menu_index: number | null
  api_id: number | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_system_menuMaxAggregateOutputType = {
  menu_id: number | null
  menu_name: string | null
  menu_icon: string | null
  menu_index: number | null
  api_id: number | null
  node_type: string | null
  parent_id: string | null
  state: string | null
  updated_at: Date | null
  created_at: Date | null
}

export type Common_system_menuCountAggregateOutputType = {
  menu_id: number
  menu_name: number
  menu_icon: number
  menu_index: number
  api_id: number
  node_type: number
  parent_id: number
  state: number
  updated_at: number
  created_at: number
  _all: number
}


export type Common_system_menuAvgAggregateInputType = {
  menu_id?: true
  menu_index?: true
  api_id?: true
}

export type Common_system_menuSumAggregateInputType = {
  menu_id?: true
  menu_index?: true
  api_id?: true
}

export type Common_system_menuMinAggregateInputType = {
  menu_id?: true
  menu_name?: true
  menu_icon?: true
  menu_index?: true
  api_id?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_system_menuMaxAggregateInputType = {
  menu_id?: true
  menu_name?: true
  menu_icon?: true
  menu_index?: true
  api_id?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
}

export type Common_system_menuCountAggregateInputType = {
  menu_id?: true
  menu_name?: true
  menu_icon?: true
  menu_index?: true
  api_id?: true
  node_type?: true
  parent_id?: true
  state?: true
  updated_at?: true
  created_at?: true
  _all?: true
}

export type Common_system_menuAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_system_menu to aggregate.
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_system_menus to fetch.
   */
  orderBy?: Prisma.common_system_menuOrderByWithRelationInput | Prisma.common_system_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.common_system_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_system_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_system_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned common_system_menus
  **/
  _count?: true | Common_system_menuCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Common_system_menuAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Common_system_menuSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Common_system_menuMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Common_system_menuMaxAggregateInputType
}

export type GetCommon_system_menuAggregateType<T extends Common_system_menuAggregateArgs> = {
      [P in keyof T & keyof AggregateCommon_system_menu]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommon_system_menu[P]>
    : Prisma.GetScalarType<T[P], AggregateCommon_system_menu[P]>
}




export type common_system_menuGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.common_system_menuWhereInput
  orderBy?: Prisma.common_system_menuOrderByWithAggregationInput | Prisma.common_system_menuOrderByWithAggregationInput[]
  by: Prisma.Common_system_menuScalarFieldEnum[] | Prisma.Common_system_menuScalarFieldEnum
  having?: Prisma.common_system_menuScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Common_system_menuCountAggregateInputType | true
  _avg?: Common_system_menuAvgAggregateInputType
  _sum?: Common_system_menuSumAggregateInputType
  _min?: Common_system_menuMinAggregateInputType
  _max?: Common_system_menuMaxAggregateInputType
}

export type Common_system_menuGroupByOutputType = {
  menu_id: number
  menu_name: string
  menu_icon: string
  menu_index: number
  api_id: number | null
  node_type: string | null
  parent_id: string
  state: string
  updated_at: Date
  created_at: Date
  _count: Common_system_menuCountAggregateOutputType | null
  _avg: Common_system_menuAvgAggregateOutputType | null
  _sum: Common_system_menuSumAggregateOutputType | null
  _min: Common_system_menuMinAggregateOutputType | null
  _max: Common_system_menuMaxAggregateOutputType | null
}

type GetCommon_system_menuGroupByPayload<T extends common_system_menuGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Common_system_menuGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Common_system_menuGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Common_system_menuGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Common_system_menuGroupByOutputType[P]>
      }
    >
  >



export type common_system_menuWhereInput = {
  AND?: Prisma.common_system_menuWhereInput | Prisma.common_system_menuWhereInput[]
  OR?: Prisma.common_system_menuWhereInput[]
  NOT?: Prisma.common_system_menuWhereInput | Prisma.common_system_menuWhereInput[]
  menu_id?: Prisma.IntFilter<"common_system_menu"> | number
  menu_name?: Prisma.StringFilter<"common_system_menu"> | string
  menu_icon?: Prisma.StringFilter<"common_system_menu"> | string
  menu_index?: Prisma.IntFilter<"common_system_menu"> | number
  api_id?: Prisma.IntNullableFilter<"common_system_menu"> | number | null
  node_type?: Prisma.StringNullableFilter<"common_system_menu"> | string | null
  parent_id?: Prisma.StringFilter<"common_system_menu"> | string
  state?: Prisma.StringFilter<"common_system_menu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_system_menu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_system_menu"> | Date | string
}

export type common_system_menuOrderByWithRelationInput = {
  menu_id?: Prisma.SortOrder
  menu_name?: Prisma.SortOrder
  menu_icon?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrderInput | Prisma.SortOrder
  node_type?: Prisma.SortOrderInput | Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_system_menuWhereUniqueInput = Prisma.AtLeast<{
  menu_id?: number
  AND?: Prisma.common_system_menuWhereInput | Prisma.common_system_menuWhereInput[]
  OR?: Prisma.common_system_menuWhereInput[]
  NOT?: Prisma.common_system_menuWhereInput | Prisma.common_system_menuWhereInput[]
  menu_name?: Prisma.StringFilter<"common_system_menu"> | string
  menu_icon?: Prisma.StringFilter<"common_system_menu"> | string
  menu_index?: Prisma.IntFilter<"common_system_menu"> | number
  api_id?: Prisma.IntNullableFilter<"common_system_menu"> | number | null
  node_type?: Prisma.StringNullableFilter<"common_system_menu"> | string | null
  parent_id?: Prisma.StringFilter<"common_system_menu"> | string
  state?: Prisma.StringFilter<"common_system_menu"> | string
  updated_at?: Prisma.DateTimeFilter<"common_system_menu"> | Date | string
  created_at?: Prisma.DateTimeFilter<"common_system_menu"> | Date | string
}, "menu_id">

export type common_system_menuOrderByWithAggregationInput = {
  menu_id?: Prisma.SortOrder
  menu_name?: Prisma.SortOrder
  menu_icon?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrderInput | Prisma.SortOrder
  node_type?: Prisma.SortOrderInput | Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.common_system_menuCountOrderByAggregateInput
  _avg?: Prisma.common_system_menuAvgOrderByAggregateInput
  _max?: Prisma.common_system_menuMaxOrderByAggregateInput
  _min?: Prisma.common_system_menuMinOrderByAggregateInput
  _sum?: Prisma.common_system_menuSumOrderByAggregateInput
}

export type common_system_menuScalarWhereWithAggregatesInput = {
  AND?: Prisma.common_system_menuScalarWhereWithAggregatesInput | Prisma.common_system_menuScalarWhereWithAggregatesInput[]
  OR?: Prisma.common_system_menuScalarWhereWithAggregatesInput[]
  NOT?: Prisma.common_system_menuScalarWhereWithAggregatesInput | Prisma.common_system_menuScalarWhereWithAggregatesInput[]
  menu_id?: Prisma.IntWithAggregatesFilter<"common_system_menu"> | number
  menu_name?: Prisma.StringWithAggregatesFilter<"common_system_menu"> | string
  menu_icon?: Prisma.StringWithAggregatesFilter<"common_system_menu"> | string
  menu_index?: Prisma.IntWithAggregatesFilter<"common_system_menu"> | number
  api_id?: Prisma.IntNullableWithAggregatesFilter<"common_system_menu"> | number | null
  node_type?: Prisma.StringNullableWithAggregatesFilter<"common_system_menu"> | string | null
  parent_id?: Prisma.StringWithAggregatesFilter<"common_system_menu"> | string
  state?: Prisma.StringWithAggregatesFilter<"common_system_menu"> | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"common_system_menu"> | Date | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"common_system_menu"> | Date | string
}

export type common_system_menuCreateInput = {
  menu_name: string
  menu_icon?: string
  menu_index?: number
  api_id?: number | null
  node_type?: string | null
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_system_menuUncheckedCreateInput = {
  menu_id?: number
  menu_name: string
  menu_icon?: string
  menu_index?: number
  api_id?: number | null
  node_type?: string | null
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_system_menuUpdateInput = {
  menu_name?: Prisma.StringFieldUpdateOperationsInput | string
  menu_icon?: Prisma.StringFieldUpdateOperationsInput | string
  menu_index?: Prisma.IntFieldUpdateOperationsInput | number
  api_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  node_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_system_menuUncheckedUpdateInput = {
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_name?: Prisma.StringFieldUpdateOperationsInput | string
  menu_icon?: Prisma.StringFieldUpdateOperationsInput | string
  menu_index?: Prisma.IntFieldUpdateOperationsInput | number
  api_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  node_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_system_menuCreateManyInput = {
  menu_id?: number
  menu_name: string
  menu_icon?: string
  menu_index?: number
  api_id?: number | null
  node_type?: string | null
  parent_id?: string
  state?: string
  updated_at?: Date | string
  created_at?: Date | string
}

export type common_system_menuUpdateManyMutationInput = {
  menu_name?: Prisma.StringFieldUpdateOperationsInput | string
  menu_icon?: Prisma.StringFieldUpdateOperationsInput | string
  menu_index?: Prisma.IntFieldUpdateOperationsInput | number
  api_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  node_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_system_menuUncheckedUpdateManyInput = {
  menu_id?: Prisma.IntFieldUpdateOperationsInput | number
  menu_name?: Prisma.StringFieldUpdateOperationsInput | string
  menu_icon?: Prisma.StringFieldUpdateOperationsInput | string
  menu_index?: Prisma.IntFieldUpdateOperationsInput | number
  api_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  node_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  parent_id?: Prisma.StringFieldUpdateOperationsInput | string
  state?: Prisma.StringFieldUpdateOperationsInput | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type common_system_menuCountOrderByAggregateInput = {
  menu_id?: Prisma.SortOrder
  menu_name?: Prisma.SortOrder
  menu_icon?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_system_menuAvgOrderByAggregateInput = {
  menu_id?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrder
}

export type common_system_menuMaxOrderByAggregateInput = {
  menu_id?: Prisma.SortOrder
  menu_name?: Prisma.SortOrder
  menu_icon?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_system_menuMinOrderByAggregateInput = {
  menu_id?: Prisma.SortOrder
  menu_name?: Prisma.SortOrder
  menu_icon?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrder
  node_type?: Prisma.SortOrder
  parent_id?: Prisma.SortOrder
  state?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type common_system_menuSumOrderByAggregateInput = {
  menu_id?: Prisma.SortOrder
  menu_index?: Prisma.SortOrder
  api_id?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}



export type common_system_menuSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  menu_id?: boolean
  menu_name?: boolean
  menu_icon?: boolean
  menu_index?: boolean
  api_id?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_system_menu"]>

export type common_system_menuSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  menu_id?: boolean
  menu_name?: boolean
  menu_icon?: boolean
  menu_index?: boolean
  api_id?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_system_menu"]>

export type common_system_menuSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  menu_id?: boolean
  menu_name?: boolean
  menu_icon?: boolean
  menu_index?: boolean
  api_id?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}, ExtArgs["result"]["common_system_menu"]>

export type common_system_menuSelectScalar = {
  menu_id?: boolean
  menu_name?: boolean
  menu_icon?: boolean
  menu_index?: boolean
  api_id?: boolean
  node_type?: boolean
  parent_id?: boolean
  state?: boolean
  updated_at?: boolean
  created_at?: boolean
}

export type common_system_menuOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"menu_id" | "menu_name" | "menu_icon" | "menu_index" | "api_id" | "node_type" | "parent_id" | "state" | "updated_at" | "created_at", ExtArgs["result"]["common_system_menu"]>

export type $common_system_menuPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "common_system_menu"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    menu_id: number
    menu_name: string
    menu_icon: string
    menu_index: number
    api_id: number | null
    node_type: string | null
    parent_id: string
    state: string
    updated_at: Date
    created_at: Date
  }, ExtArgs["result"]["common_system_menu"]>
  composites: {}
}

export type common_system_menuGetPayload<S extends boolean | null | undefined | common_system_menuDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload, S>

export type common_system_menuCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<common_system_menuFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Common_system_menuCountAggregateInputType | true
  }

export interface common_system_menuDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['common_system_menu'], meta: { name: 'common_system_menu' } }
  /**
   * Find zero or one Common_system_menu that matches the filter.
   * @param {common_system_menuFindUniqueArgs} args - Arguments to find a Common_system_menu
   * @example
   * // Get one Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends common_system_menuFindUniqueArgs>(args: Prisma.SelectSubset<T, common_system_menuFindUniqueArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Common_system_menu that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {common_system_menuFindUniqueOrThrowArgs} args - Arguments to find a Common_system_menu
   * @example
   * // Get one Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends common_system_menuFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, common_system_menuFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_system_menu that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuFindFirstArgs} args - Arguments to find a Common_system_menu
   * @example
   * // Get one Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends common_system_menuFindFirstArgs>(args?: Prisma.SelectSubset<T, common_system_menuFindFirstArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Common_system_menu that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuFindFirstOrThrowArgs} args - Arguments to find a Common_system_menu
   * @example
   * // Get one Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends common_system_menuFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, common_system_menuFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Common_system_menus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Common_system_menus
   * const common_system_menus = await prisma.common_system_menu.findMany()
   * 
   * // Get first 10 Common_system_menus
   * const common_system_menus = await prisma.common_system_menu.findMany({ take: 10 })
   * 
   * // Only select the `menu_id`
   * const common_system_menuWithMenu_idOnly = await prisma.common_system_menu.findMany({ select: { menu_id: true } })
   * 
   */
  findMany<T extends common_system_menuFindManyArgs>(args?: Prisma.SelectSubset<T, common_system_menuFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Common_system_menu.
   * @param {common_system_menuCreateArgs} args - Arguments to create a Common_system_menu.
   * @example
   * // Create one Common_system_menu
   * const Common_system_menu = await prisma.common_system_menu.create({
   *   data: {
   *     // ... data to create a Common_system_menu
   *   }
   * })
   * 
   */
  create<T extends common_system_menuCreateArgs>(args: Prisma.SelectSubset<T, common_system_menuCreateArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Common_system_menus.
   * @param {common_system_menuCreateManyArgs} args - Arguments to create many Common_system_menus.
   * @example
   * // Create many Common_system_menus
   * const common_system_menu = await prisma.common_system_menu.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends common_system_menuCreateManyArgs>(args?: Prisma.SelectSubset<T, common_system_menuCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Common_system_menus and returns the data saved in the database.
   * @param {common_system_menuCreateManyAndReturnArgs} args - Arguments to create many Common_system_menus.
   * @example
   * // Create many Common_system_menus
   * const common_system_menu = await prisma.common_system_menu.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Common_system_menus and only return the `menu_id`
   * const common_system_menuWithMenu_idOnly = await prisma.common_system_menu.createManyAndReturn({
   *   select: { menu_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends common_system_menuCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, common_system_menuCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Common_system_menu.
   * @param {common_system_menuDeleteArgs} args - Arguments to delete one Common_system_menu.
   * @example
   * // Delete one Common_system_menu
   * const Common_system_menu = await prisma.common_system_menu.delete({
   *   where: {
   *     // ... filter to delete one Common_system_menu
   *   }
   * })
   * 
   */
  delete<T extends common_system_menuDeleteArgs>(args: Prisma.SelectSubset<T, common_system_menuDeleteArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Common_system_menu.
   * @param {common_system_menuUpdateArgs} args - Arguments to update one Common_system_menu.
   * @example
   * // Update one Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends common_system_menuUpdateArgs>(args: Prisma.SelectSubset<T, common_system_menuUpdateArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Common_system_menus.
   * @param {common_system_menuDeleteManyArgs} args - Arguments to filter Common_system_menus to delete.
   * @example
   * // Delete a few Common_system_menus
   * const { count } = await prisma.common_system_menu.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends common_system_menuDeleteManyArgs>(args?: Prisma.SelectSubset<T, common_system_menuDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_system_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Common_system_menus
   * const common_system_menu = await prisma.common_system_menu.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends common_system_menuUpdateManyArgs>(args: Prisma.SelectSubset<T, common_system_menuUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Common_system_menus and returns the data updated in the database.
   * @param {common_system_menuUpdateManyAndReturnArgs} args - Arguments to update many Common_system_menus.
   * @example
   * // Update many Common_system_menus
   * const common_system_menu = await prisma.common_system_menu.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Common_system_menus and only return the `menu_id`
   * const common_system_menuWithMenu_idOnly = await prisma.common_system_menu.updateManyAndReturn({
   *   select: { menu_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends common_system_menuUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, common_system_menuUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Common_system_menu.
   * @param {common_system_menuUpsertArgs} args - Arguments to update or create a Common_system_menu.
   * @example
   * // Update or create a Common_system_menu
   * const common_system_menu = await prisma.common_system_menu.upsert({
   *   create: {
   *     // ... data to create a Common_system_menu
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Common_system_menu we want to update
   *   }
   * })
   */
  upsert<T extends common_system_menuUpsertArgs>(args: Prisma.SelectSubset<T, common_system_menuUpsertArgs<ExtArgs>>): Prisma.Prisma__common_system_menuClient<runtime.Types.Result.GetResult<Prisma.$common_system_menuPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Common_system_menus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuCountArgs} args - Arguments to filter Common_system_menus to count.
   * @example
   * // Count the number of Common_system_menus
   * const count = await prisma.common_system_menu.count({
   *   where: {
   *     // ... the filter for the Common_system_menus we want to count
   *   }
   * })
  **/
  count<T extends common_system_menuCountArgs>(
    args?: Prisma.Subset<T, common_system_menuCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Common_system_menuCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Common_system_menu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Common_system_menuAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Common_system_menuAggregateArgs>(args: Prisma.Subset<T, Common_system_menuAggregateArgs>): Prisma.PrismaPromise<GetCommon_system_menuAggregateType<T>>

  /**
   * Group by Common_system_menu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {common_system_menuGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends common_system_menuGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: common_system_menuGroupByArgs['orderBy'] }
      : { orderBy?: common_system_menuGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, common_system_menuGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommon_system_menuGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the common_system_menu model
 */
readonly fields: common_system_menuFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for common_system_menu.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__common_system_menuClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the common_system_menu model
 */
export interface common_system_menuFieldRefs {
  readonly menu_id: Prisma.FieldRef<"common_system_menu", 'Int'>
  readonly menu_name: Prisma.FieldRef<"common_system_menu", 'String'>
  readonly menu_icon: Prisma.FieldRef<"common_system_menu", 'String'>
  readonly menu_index: Prisma.FieldRef<"common_system_menu", 'Int'>
  readonly api_id: Prisma.FieldRef<"common_system_menu", 'Int'>
  readonly node_type: Prisma.FieldRef<"common_system_menu", 'String'>
  readonly parent_id: Prisma.FieldRef<"common_system_menu", 'String'>
  readonly state: Prisma.FieldRef<"common_system_menu", 'String'>
  readonly updated_at: Prisma.FieldRef<"common_system_menu", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"common_system_menu", 'DateTime'>
}
    

// Custom InputTypes
/**
 * common_system_menu findUnique
 */
export type common_system_menuFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_system_menu to fetch.
   */
  where: Prisma.common_system_menuWhereUniqueInput
}

/**
 * common_system_menu findUniqueOrThrow
 */
export type common_system_menuFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_system_menu to fetch.
   */
  where: Prisma.common_system_menuWhereUniqueInput
}

/**
 * common_system_menu findFirst
 */
export type common_system_menuFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_system_menu to fetch.
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_system_menus to fetch.
   */
  orderBy?: Prisma.common_system_menuOrderByWithRelationInput | Prisma.common_system_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_system_menus.
   */
  cursor?: Prisma.common_system_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_system_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_system_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_system_menus.
   */
  distinct?: Prisma.Common_system_menuScalarFieldEnum | Prisma.Common_system_menuScalarFieldEnum[]
}

/**
 * common_system_menu findFirstOrThrow
 */
export type common_system_menuFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_system_menu to fetch.
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_system_menus to fetch.
   */
  orderBy?: Prisma.common_system_menuOrderByWithRelationInput | Prisma.common_system_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for common_system_menus.
   */
  cursor?: Prisma.common_system_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_system_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_system_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_system_menus.
   */
  distinct?: Prisma.Common_system_menuScalarFieldEnum | Prisma.Common_system_menuScalarFieldEnum[]
}

/**
 * common_system_menu findMany
 */
export type common_system_menuFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter, which common_system_menus to fetch.
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of common_system_menus to fetch.
   */
  orderBy?: Prisma.common_system_menuOrderByWithRelationInput | Prisma.common_system_menuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing common_system_menus.
   */
  cursor?: Prisma.common_system_menuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` common_system_menus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` common_system_menus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of common_system_menus.
   */
  distinct?: Prisma.Common_system_menuScalarFieldEnum | Prisma.Common_system_menuScalarFieldEnum[]
}

/**
 * common_system_menu create
 */
export type common_system_menuCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * The data needed to create a common_system_menu.
   */
  data: Prisma.XOR<Prisma.common_system_menuCreateInput, Prisma.common_system_menuUncheckedCreateInput>
}

/**
 * common_system_menu createMany
 */
export type common_system_menuCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many common_system_menus.
   */
  data: Prisma.common_system_menuCreateManyInput | Prisma.common_system_menuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_system_menu createManyAndReturn
 */
export type common_system_menuCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * The data used to create many common_system_menus.
   */
  data: Prisma.common_system_menuCreateManyInput | Prisma.common_system_menuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * common_system_menu update
 */
export type common_system_menuUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * The data needed to update a common_system_menu.
   */
  data: Prisma.XOR<Prisma.common_system_menuUpdateInput, Prisma.common_system_menuUncheckedUpdateInput>
  /**
   * Choose, which common_system_menu to update.
   */
  where: Prisma.common_system_menuWhereUniqueInput
}

/**
 * common_system_menu updateMany
 */
export type common_system_menuUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update common_system_menus.
   */
  data: Prisma.XOR<Prisma.common_system_menuUpdateManyMutationInput, Prisma.common_system_menuUncheckedUpdateManyInput>
  /**
   * Filter which common_system_menus to update
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * Limit how many common_system_menus to update.
   */
  limit?: number
}

/**
 * common_system_menu updateManyAndReturn
 */
export type common_system_menuUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * The data used to update common_system_menus.
   */
  data: Prisma.XOR<Prisma.common_system_menuUpdateManyMutationInput, Prisma.common_system_menuUncheckedUpdateManyInput>
  /**
   * Filter which common_system_menus to update
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * Limit how many common_system_menus to update.
   */
  limit?: number
}

/**
 * common_system_menu upsert
 */
export type common_system_menuUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * The filter to search for the common_system_menu to update in case it exists.
   */
  where: Prisma.common_system_menuWhereUniqueInput
  /**
   * In case the common_system_menu found by the `where` argument doesn't exist, create a new common_system_menu with this data.
   */
  create: Prisma.XOR<Prisma.common_system_menuCreateInput, Prisma.common_system_menuUncheckedCreateInput>
  /**
   * In case the common_system_menu was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.common_system_menuUpdateInput, Prisma.common_system_menuUncheckedUpdateInput>
}

/**
 * common_system_menu delete
 */
export type common_system_menuDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
  /**
   * Filter which common_system_menu to delete.
   */
  where: Prisma.common_system_menuWhereUniqueInput
}

/**
 * common_system_menu deleteMany
 */
export type common_system_menuDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which common_system_menus to delete
   */
  where?: Prisma.common_system_menuWhereInput
  /**
   * Limit how many common_system_menus to delete.
   */
  limit?: number
}

/**
 * common_system_menu without action
 */
export type common_system_menuDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the common_system_menu
   */
  select?: Prisma.common_system_menuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the common_system_menu
   */
  omit?: Prisma.common_system_menuOmit<ExtArgs> | null
}
